### ISSUE TITLE
Email registration does not work through proxy

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#1522]
Or any time when the IP of the connecting device is rewritten somehow: 
- Proxying
- NATting
- VPN
  etc.

This worked in 5.7 seemingly.

**Comment by julsemaan** [comment]
Already started looking into it before the issue was opened so I'll grab it from @jrouzierinverse

**Comment by julsemaan** [comment]
Just looked into the reasons that led to this.

The unregistration date is stored in the user session since it is not stored inside the activation record.

It worked in in 5.7 because it would always take the unregistration date inside the `email` source even though it was not the source that was used in the registration process. This meant that if you used two email sources on two different portal profiles, the one named `email` would determine the role + unregdate of the user ignoring any other one you could have defined.

The only good way is to store the unregdate inside the activation record since we take the MAC from the activation record.
