### ISSUE TITLE
Immunize critical processes from oomkiller

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence#1684]
Here is how to do it.
http://backdrift.org/oom-killer-how-to-create-oom-exclusions-in-linux

Opening a ticket so we can list what should never be killed when a system is out of memory.
sshd and mysql should be in that list. You see any other?

**Comment by tlaurion** [comment]
[Article](http://backdrift.org/oom-killer-how-to-create-oom-exclusions-in-linux) suggests to create crontabs to immunize each desired process (pids can change) against overcommited memory by the kernel (symptom). 

That would give:

```
*/1 * * * * root pgrep -f "/usr/sbin/sshd" | while read PID; do echo -17 > /proc/$PID/oom_adj; done
*/1 * * * * root pgrep -f "/usr/libexec/mysqld" | while read PID; do echo -17 > /proc/$PID/oom_adj; done
```

Could also be done with monit.

**Comment by tlaurion** [comment]
Or we could want to control the source of the problem, which is that the kernel [Memory Overcommitment is optimistic](https://www.win.tue.nl/~aeb/linux/lk/lk-9.html#ss9.6), resulting in oom_killer needing to cleanup overcommited memory permitted by the kernel.

On CentOS7:

```
uname -r
3.10.0-327.36.1.el7.x86_64
cat /proc/sys/vm/overcommit_memory 
0
cat /proc/sys/vm/overcommit_ratio 
50
```

[Kernel documentation](https://www.kernel.org/doc/Documentation/sysctl/vm.txt) exerpt:

```
==============================================================

overcommit_memory:

This value contains a flag that enables memory overcommitment.

When this flag is 0, the kernel attempts to estimate the amount
of free memory left when userspace requests more memory.

When this flag is 1, the kernel pretends there is always enough
memory until it actually runs out.

When this flag is 2, the kernel uses a "never overcommit"
policy that attempts to prevent any overcommit of memory.
Note that user_reserve_kbytes affects this policy.

This feature can be very useful because there are a lot of
programs that malloc() huge amounts of memory "just-in-case"
and don't use much of it.

The default value is 0.

See Documentation/vm/overcommit-accounting and
mm/mmap.c::__vm_enough_memory() for more information.

==============================================================

overcommit_ratio:

When overcommit_memory is set to 2, the committed address
space is not permitted to exceed swap plus this percentage
of physical RAM.  See above.
```

[Experimentations](https://www.win.tue.nl/~aeb/linux/lk/lk-9.html#ss9.6) with those concepts.

[Other reports of change](url)

**Comment by tlaurion** [comment]
But since we do not "control" other programs, it may be safer to only protect crtitical applications against oom_killer then try to control the system. Here is an [example](https://serverfault.com/questions/606185/how-does-vm-overcommit-memory-work) of applying  the "never overcommit" (2 instead of the default 0) policy to a system that has applications which mallocs a lot (Amarok music player) which needs to put overcommit_ratio to 300% (instead of 50 being the default). 

That wouldn't help us.

**Comment by extrafu** [comment]
I think we should have a monit script that sets this properly every single minute.

We could protect processes like these from being killed:
- httpd-aaa
- radiusd-acct/auth/...
- mysql
- pfdns

But we could like permit a kill of the pfdhcplisteners, pfqueue (probably), httpd-portal, etc.

The idea is a kill shouldn't make PacketFence go ape-shit. It could prevent the registration process from working properly, but it shouldn't affect real users (802.1X, registered users, etc.).

**Comment by jrouzierinverse** [comment]
We should also add the redis_queue and redis_cache services.

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by julsemaan** [comment]
I think redis_queue is expandable since it is not critical for service.

Otherwise at this rate, we'll be protecting all processes except kworker :)

I would even strike out pfdns and keep:
- MySQL
- RADIUS load balancer + auth (no acct)
- httpd.aaa

These are the critical processes for 802.1x that should never ever be killed (especially MySQL).

We could live with a kill of any other service as it will be started back up a few seconds after it dies.

**Comment by julsemaan** [comment]
To add to the list above, I forgot redis_cache which @jrouzierinverse is right that we should protect almost as much as MySQL

**Comment by jrouzierinverse** [comment]
In some scenarios httpd.aaa will fail if redis_queue is not there such 
as changing the status of the node.
So either we immunize httpd.aaa from failing when redis_queue is not 
available or we immunize redis_queue.

Which approach do you think is best?
- immunize redis_queue.
- httpd.aaa from failing when redis_queue is not available

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

**Comment by louismunro** [comment]
This is all well and good in the short term.
In the medium term we need to address the issue at the root.
The httpd processes are too fat.

We should make it a goal to use less memory.
We should set ambitious targets because the current usage is unsustainable.

**Comment by julsemaan** [comment]
@jrouzierinverse 
I would say we should immunize httpd.aaa (and all processes actually) from redis_queue being dead since failure of a 'notify' shouldn't make the code die IMO.
That was the behavior when httpd.webservices was our poor-mans queue and IMO that failure resistance should be ported to redis_queue
In all cases I know of, a notify doesn't affect critical service directly so code shouldn't die because its unavailable

@louismunro 
Fully agree, its starting to get ridiculous...
Thing is, perl memory is not easy to debug which explains the small gains we have made so far

**Comment by louismunro** [comment]
@julsemaan Then perhaps we have our (not short term) answer...

**Comment by tlaurion** [comment]
On a master active/active node,  `echo 350 > /proc/sys/vm/overcommit_ratio` (350%) was required to be able to execute additional commands when `echo 2 > /proc/sys/vm/overcommit_memory` (never overcommit) is enforced.

**Comment by julsemaan** [comment]
Don't just close issues without stating whether or not they were fixed and what is the fix if it exists.

Don't have to point to the precise commit but at least just where that would be which in this case would be that it was addressed via the monit script generator we have in addons/monit

Otherwise, people will be happy af when they find this issue but sad af when they realize it was just closed without an explanation of the fix we put in place

Think of it like if you were zayme in front of a mustard+turkey sandwich store but you would realize that they are out of mustard, turkey and bread. That's how I would feel when looking at this issue.

**Comment by tlaurion** [comment]
@julsemaan Ok!
