### ISSUE TITLE
dhcp in cluster

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#2107]
You need to have a dhcp pool active in isolation if you want to enable DHCP for registration of a routed network in a cluster environment.

Step to reproduce:
-In a cluster environement,
-Disable DHCP on isolation/Registration Interface
-Add a routed network with DHCP enable in registration
-try to start dhcpd => should fail
-Add a routed network with DHCP enable in isolation
-try to start dhcpd => should work

**Comment by julsemaan** [comment]
I investigated and the issue comes from the config generation of dhcpd.conf

That generation doesn't take into account the possibility an interface wouldn't be dhcpd enabled when its registration or isolation when declaring the failover peer

Would require reworking the whole generation of config to untangle everything which I'm not sure is worth it knowing we might get rid of ISC dhcp soon

Pushing milestone to 7.2 and we'll readdress it then

**Comment by dwlfrth** [comment]
Will be addressed with pfdhcp in golang
