### ISSUE TITLE
update graphite to fix combination of metrics from all servers

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2170]
@louismunro discovered there was a bug in graphite which prevents the version we use from polling the metrics from other servers.

This makes us put the replication factor to the size of the cluster which is inefficient.

We should update our version of graphite so it polls metrics from other servers

**Comment by julsemaan** [comment]
This is the continuation of #2137

**Comment by louismunro** [comment]
To be precise the issue is not that it can't poll from other servers, it's that it will use the first server that responds for that data.
Unfortunately there is no guarantee that the server that is first to respond has a full set of data.
And graphite will not query multiple servers for a single dataset if there are missing datapoints.

I believe this was fixed in a later release of graphite.
Repackaging that version would be a good thing, but it's too late for 7.0.
Will include it in the 7.1 TODO list.

**Comment by julsemaan** [comment]
graphite has been removed

**Comment by louismunro** [comment]
Yay! 🥇 
😉
