### ISSUE TITLE
PF Admin: Microsoft Active Directory Domains naming

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2183]
Shouldn't we use "Domains" rather than "Microsoft Active Directory Domains" ?
I mean, we should be able to join a Samba domain using the same procedure ?

**Comment by julsemaan** [comment]
I agree and disagree

I agree because from a tech standpoint you're right

But from a usability standpoint, using 'Active Directory' makes things clearer

I'd personally go with 'Active Directory Domains' and remove the Microsoft

This way that unties it from Microsoft and ties it more to the different Active Directory protocols which are implemented by Samba

And it will make the name shorter which will improve display

**Comment by louismunro** [comment]
Active Directory Domain it is then.

**Comment by whitx** [comment]
fixed by dc7c622
