### ISSUE TITLE
pfmon upgrade script: should we delete the maintenance section

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2188]
Given the amount of different parameters in that section and the possibility of mistake by the upgrade script, should we leave the maintenance section there after the script does its thing and instruct the user to delete it ?

Currently it removes the section from pf.conf

**Comment by jrouzierinverse** [comment]
Just delete since it will cause checkup warnings.

The naming of the fields in pfmon.conf where based off the naming in the pf.conf.
So there is a one to one mapping expect for iplog_cleanup => ip4log_cleanup. 
Which is now fixed.

Also we can always backup pf.conf in the script or instruct them to do some in the UPGRADE notes.

**Comment by dwlfrth** [comment]
We should efface something from ce sectionnage
