### ISSUE TITLE
Dropping dpkg-distribution in favour of /etc/os-release

### ISSUE THREAD

**Issue by ghost** [inverse-inc/packetfence#2392]
Hi,

I see that in the debian packaging of packetfence you use dpkg-distribution as a local hack. Would you accept a patch to drop dpkg-distirbution in favour of parsing /etc/os-release?

Regards,
Daniel

**Comment by louismunro** [comment]
I am a little bit naive about debian packaging admittedly, but may I ask why that would be preferable?

**Comment by julsemaan** [comment]
Closing for now

@daniel-baumann, if you want to provide an answer to the question @louismunro asked, feel free to reopen this

**Comment by polynamaude** [comment]
@louismunro It would be better because you wouldn't ask people to install a specific software other than what's already in the Debian distribution. In this way, you could even get your software into the standard Debian distribution because it would be policy compliant. Well I'd need to get a closer look into the copyright but you'll simply make life easier for others ;-)

**Comment by nqb** [comment]
Another possibility is to use `lsb_release` from package `lsb-release`.
