### ISSUE TITLE
read-only mode: Saving configuration parameters

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2464]
Even by being in a read-only mode on a database point-of-view, it should be possible to save some configuration changes.

Some of them needs to be excluded from that logic since requires duplication in the database:
- switches
- roles
- violations

See #2458

**Comment by dwlfrth** [comment]
@jrouzierinverse

**Comment by jrouzierinverse** [comment]
This should be discussed on exactly what we want here.

There one edge cases that should be either documented or dealt with in code.
When a config (violations, switches and roles) that is sync against the database is modified what should be done?

Because after the db goes back online a config reload needs to happen or those changes will be applied.
