### ISSUE TITLE
vlan_filter: EAP-Type filter documentation

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2532]
'EAP-Type' => 13,
instead of 
'EAP-Type' => TLS,

**Comment by dwlfrth** [comment]
That's more a doc issue than an actual issue.
It is not clear what value should be used as a filter value when it comes to EAP-Type filter.
That should probably be addressed by a better representation / handling of filter engines in the GUI otherwise it will simply get lost somewhere not maintained.

**Comment by jrouzierinverse** [comment]
Fixed in 96a3234a215b345191a83ea4bec81aee34745e48.
Since now EAP-Type will match as the string or number the generic radius filter instructions applies.

**Comment by julsemaan** [comment]
So @jrouzierinverse, does that mean this should be closed?

**Comment by jrouzierinverse** [comment]
Yes unless you disagree.

**Comment by julsemaan** [comment]
All good closing if its fixed
