### ISSUE TITLE
mariadb clustering: RO mode

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2593]
As per @julsemaan:
We currently have issues where a small percentage of reconnects between Galera cluster instances fails and has a member excluded or the database mistakenly put into read-only mode.

We are currently using a home-made script to set the read only flag which requires to temporarily disable wsrep and then turn it back on right after.

I'm suspecting that when the cluster is unstable for a very short amount of time, this can cause a member to change its view of the cluster state mistakenly and then the only way to recover is to do a full DB resync.

The more I look into this, the more I realize we don't need to put the DB in read only more and could simply look if wsrep_ready is on or off since it represents how galera sees its state in the cluster.

This will obviously require testing to confirm it doesn't have side effects but it all seems possible and would allow us to rely on a galera cluster stack that is closer to the one that is official (the read-only script we use is unofficial and contains adjustments I did which may not be compatible with some galera internal logic)

**Comment by julsemaan** [comment]
We currently have issues where a small percentage of reconnects between Galera cluster instances fails and has a member excluded or the database mistakenly put into read-only mode.

We are currently using a home-made script to set the read only flag which requires to temporarily disable wsrep and then turn it back on right after.

I'm suspecting that when the cluster is unstable for a very short amount of time, this can cause a member to change its view of the cluster state mistakenly and then the only way to recover is to do a full DB resync.

The more I look into this, the more I realize we don't need to put the DB in read only more and could simply look if wsrep_ready is on or off since it represents how galera sees its state in the cluster.

This will obviously require testing to confirm it doesn't have side effects but it all seems possible and would allow us to rely on a galera cluster stack that is closer to the one that is official (the read-only script we use is unofficial and contains adjustments I did which may not be compatible with some galera internal logic)
