### ISSUE TITLE
Follow the NAS identifier (AP name) for a node in a single screen

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#2832]
When troubleshooting someone's wireless connection, the NAS identifier is very helpful in the Auditing section; however, to be able to watch a node's connection move from AP to AP I have to click into multiple Auditing entries (and too many mouse clicks hurts my brittle finger!).  I could see it be helpful to Admins to do one of the following:

- Add a 'NAS identifier' column to the 'Auditing' section
- Add 'NAS identifier' to the IPv4 Address log for the node
- Add 'Nas identifier' to the Location log for the node

**Comment by veedubbs** [comment]
@julsemaan I'm sure this just simply wasn't seen with all the 8.0 development work going on, but I (obviously) think it'd be a helpful feature.

What does Inverse think?

**Comment by julsemaan** [comment]
Yeah I think we totally missed that one, probably was too busy thinking about Christmas parties when that one was opened.

Adding the column in the auditing section is very easy since we already have the info.

Adding it to the locationlog would also be a good idea (although a tiny bit less easy because we're not collecting it right now)

Adding it to the IPv4 log entry of the node though doesn't make much sense because the NAS Identifier doesn't matter for that entry.

I think by adding it to the location entry and displaying it in the location tab, it should accomplish the goal of reducing the amount of clicking needed to get the NAS ID info.

I'll tag that as a 8.1 since the window for 8.0 features is over

**Comment by veedubbs** [comment]
Could you do both in the Auditing section and in the location tab?

**Comment by julsemaan** [comment]
Yes, we can add the NAS ID in the auditing section columns as well, especially if its already collected.

8.1 may see a new admin interface though so we may opt with the ability to be able to pick the columns you want to display like in the nodes (#1138)
