### ISSUE TITLE
Email registration: Address regression of temporary email activation message

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2836]
Introduced in 6308b6b4c995478d512e98e8d7797c23b002ae8d

The timeout was put on customers request so we would need to keep it by adjusting the i18n to use variables instead of removing it

**Comment by jrouzierinverse** [comment]
@julsemaan  

Since you are more familiar with that code I need this question answered.
Would there ever be a case where email_timeout is not defined?

If it was always defined then we can just use a single translation.

If email_timeout can be defined or undefined then we would need two translations.

**Comment by julsemaan** [comment]
It is only defined when its an email source, so it might have been checking whether or not its defined because formhandler was calling that code path even though the field wasn't part of the rendered fields (since its still part of the form)

We could move the return of the rendered HTML inside the 'if' where the timeout is always defined and render an HTML comment otherwise.

**Comment by jrouzierinverse** [comment]
If the email_timeout is not defined could we just render it as an empty string?
So we do not have to worry about it.

**Comment by julsemaan** [comment]
@jrouzierinverse 

That works also, whatever is easier for you, both sound good
