### ISSUE TITLE
Validation failed for 'ArrayRef[Str] in PF7.4

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#2916]
Seen in logs/httpd.admin.log on a customer standalone server:
`an 29 14:25:32 t7packetfence httpd_admin: httpd.admin(13830) DEBUG: [mac:unknown] Attribute (realms) does not pass the type constraint because: Validation failed for 'ArrayRef[Str]' with value default at constructor pf::Authentication::Source::ADSource::new (defined at /usr/local/pf/lib/pf/Authentication/Source/ADSource.pm line 96) line 192, line 1003.`

**Comment by julsemaan** [comment]
@jrouzierinverse 

Could you look into this for an eventual 7.4.1 early next week

And @TomInverse  I guess we might need a bit more context around how to replicate this error

**Comment by jrouzierinverse** [comment]
I think this happened because someone did not following the upgrade guide properly.

**Comment by julsemaan** [comment]
Those users, always not following the upgrade guide.

I think your wild guess might be right, its probably missing the new realms attribute.

Not sure what to do about it if that is the case, should the realms be defaulted to empty?
Or should we stick to saying, you don't follow the upgrade guide, you get weird stuff.

I'd go with the last option since to me its similar as not applying the schema upgrade, if you don't do it, then you'll get MySQL errors and that is perfectly normal

**Comment by extrafu** [comment]
+1 on pointing the users back to the upgrade instructions.

**Comment by fdurand** [comment]
I am able to reproduce it.

**Comment by julsemaan** [comment]
@jrouzierinverse 

What are we doing with this ?

**Comment by fdurand** [comment]
It happen when you click on Test in a AD/Ldap authentication source.

**Comment by jrouzierinverse** [comment]
It was previously thought that the upgrade guide was not followed.
In what scenario it happened?

**Comment by jrouzierinverse** [comment]
I am not able to replicate this on an new install 7.4.
Can you replicate this?
