### ISSUE TITLE
Content-Security-Policy header in 7.4.0 breaks the captive portal due to inline script tags

### ISSUE THREAD

**Issue by Zappatron** [inverse-inc/packetfence#2921]
After upgrading from 7.2.0 to 7.4.0 I noticed the captive portal stopped redirecting. The developer tools in chrome tell me it is refusing to run the inline script due to the CSP header.

You can see many errors in the console when viewing the 7.4.0 captive portal in the lastest version chrome. 

I have worked around the issue by commenting the line below and restarting packetfence

```
# diff ./html/captive-portal/lib/captiveportal.pm.orig ./html/captive-portal/lib/captiveportal.pm
142c142
<     $c->response->header('Content-Security-Policy' => "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' http://$captive_portal_network_detection_ip/; style-src 'self'; font-src 'self';");
---
>     #$c->response->header('Content-Security-Policy' => "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' http://$captive_portal_network_detection_ip/; style-src 'self'; font-src 'self';");

```

**Comment by julsemaan** [comment]
The CSP headers should have been disabled for the portal before the release but they weren't which is what causes your issue when using some custom inline scripting or CSS.

Instead of commenting the line, you can go in "System Configuration->Main Configuration->Advanced" and uncheck the portal CSP security headers there.

This way your change will be upgrade proof and not have to touch the codebase.

I will push the setting to being disabled by default in the maintenance branch

**Comment by Zappatron** [comment]
Oh nice. Are you saying the captive portal template has been updated to be compatible with the CSP headers?

If so, how do I get the updated template?

**Comment by julsemaan** [comment]
The updated templates should indeed be compatible with CSP.

in order to ensure you have the latest templates, you could delete any overridden templates in html/captive-portal/profile-templates/NAME_OF_PROFILE/

Then put any custom you had in the templates again through the admin interface and you should be golden

**Comment by Zappatron** [comment]
Great thanks I'll take a look at that - possibly worth updating the upgrade docs to mention it?

**Comment by julsemaan** [comment]
@Zappatron 

It shouldn't have hit the release so that is why its missing, I'll make sure I add it since it will now be part of the base 7.4.0 install

Potentially a 7.4.1 to launch in a week or two containing the lastest fixes for v7 so the last package it has is as stable as possible

**Comment by julsemaan** [comment]
I've pushed the CSP to disabled by default in maintenance/7.4

4bbcf78140c41d8189caa08802d5b9415dd95dc1

**Comment by julsemaan** [comment]
I think for now I'll leave out the upgrade guide note and we'll instead aim for a 7.4.1 with a few fixes early next week including this one

**Comment by jrouzierinverse** [comment]
Should we do the same in devel or just close this issue?

**Comment by julsemaan** [comment]
I think the goal is to leave the CSP headers enabled for the portal, so we should probably put the fix in devel

**Comment by jrouzierinverse** [comment]
The fix placed in maintenance was to disable CSP headers.
What are the other fixed?

**Comment by julsemaan** [comment]
I thought there was an actual fix in the description of this issue by looking too quickly

This can indeed be closed
