### ISSUE TITLE
Historical graph of total number of online nodes

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#2924]
Since PacketFence can already keep track of the online/offline status of nodes, would it be possible to have a historical graph of online nodes at certain times?  For example, if I want to compare the amount of nodes on my network at Noon today versus Noon yesterday (maybe also differentiate wired versus wireless nodes...?).

I know you can currently go to the **Nodes** tab and do a query for _Online Between_.  What I'm really interested in is a graph, much like the **Nodes States** report, but for Online Nodes.  Is this already possible in PF, and I'm just missing something?  I don't think a graph like this currently exists....?

**Comment by julsemaan** [comment]
I think this used to exist or at least be in our pipeline at some point.

Maybe the metric is still kept but just not displayed

I think its a good idea to have that.

If my memory is good @jrouzierinverse was the one who did it back in PF 5.something

@jrouzierinverse is this still tracked but just not displayed ? Or did it just never exist and I'm going a bit crazy ?

**Comment by julsemaan** [comment]
@satkunas 

Is this covered by #3113 ?

**Comment by satkunas** [comment]
@julsemaan not directly. I assume from the OP that @veedubbs wants to have the "last 24 hours" side-by-side with "24 hours to 48 hours ago". However, I think one could abstract a comparison between dates if we provide charts with longer timeframes, such as day`, `week`, `month` and `year` - much like we did with registrations - so the metrics can be compared on the same chart(s) side-by-side.

Currently the `total online devices` chart shows the number of devices online over the last 1 hour. We could add one or more of the following charts very easily with the current functionality:
 - `total online devices for the last day`
 - `total online devices for the last week`
 - `total online devices for the last month`
 - `total online devices for the last year`

...depending on how far back we want to offer such an abstraction.

> differentiate wired versus wireless nodes

This is currently not possible with our given MySQL indexes. We would need to create a `type` ENUM (`wired`,`wireless`) column, create a new `INDEX` on that column, and modify perl to statically populate this column during the `INSERT` statement - in order to avoid a slow `FULLTEXT` lookup on the table. Then we could produce wired/wireless statsd metrics from this table.

**Comment by veedubbs** [comment]
@satkunas @julsemaan I guess I was looking for snapshots of online nodes at given times.  i.e., how many nodes were online this Monday at 10am, and last Monday at 10am...and two Mondays ago at 10am.  Then I could compare the data over time and potentially see a trend in growth.

This could seemingly be endless though (i.e., snapshots at every hour of the day or every 15 minutes...?).  I'll leave it up to Inverse to figure out if this is possible, feasible, etc...

Thanks!

**Comment by julsemaan** [comment]
@satkunas 

I don't think this issues requires a difference between wired/wireless so I believe we can leave this aside.

I think that by simply having a gauge that checks how many devices are online currently and recording this every 15 minutes in a gauge, we can accomplish the goal of this issue.

Only think will be to adjust retention of our graphs since by default it 24 hours so that one would need to be kept for a bit longer

**Comment by satkunas** [comment]
15 minutes = 900 seconds
3600 samples * 900 seconds = 3240000 seconds total = 37.5 days total

@julsemaan I'll adjust the online/offline charts to be 1 month (30 days) of data - with a sample every 12 minutes.

1 month = (60 * 60 * 24 * 30) = 2592000 seconds
2592000 seconds / 3600 samples = 720 seconds/sample = 12 minutes/sample
