### ISSUE TITLE
pfstats: Error while contacting API

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3119]
There is an error that pfstats is getting:
```
Apr 12 09:28:51 pf-julien /usr/local/pf/bin/pfstats[19752]: t=2018-04-12T09:28:51-0400 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/dhcp/stats/enp0s8" pid=19752
Apr 12 09:28:51 pf-julien /usr/local/pf/bin/pfstats[19752]: t=2018-04-12T09:28:51-0400 lvl=eror msg="API error" pid=19752 Error body doesn't follow the Unified API standard, couldn't extract the error message from it.=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
```

First, the log line should be concatenated using `+` instead of through the arguments send to the logger.

Then we need to find where that non standard error is coming from and make it standard.

**Comment by satkunas** [comment]
@julsemaan I think this is a panic from `dhcp` that's causing `panichandler` to dump output: https://github.com/inverse-inc/packetfence/blob/devel/go/panichandler/panichandler.go#L18

I noticed it occurs when referencing an interface that doesn't exist, but I never traced it any further.

The `API error` is generated because `panichandler` doesn't output expected JSON.

I could look at tracing it, and possibly adjust the panichandler's output, but I believe @jrouzierinverse might be better suited to look at it instead.

**Comment by julsemaan** [comment]
I think we should add a new HttpJson panic handler that returns the unified API standard error format and we could use it in our API based services. Let me know if you need more details than that.

On top of that, we should fix pfdhcp so that it outputs a proper error when calling an unknown interface

**Comment by satkunas** [comment]
@julsemaan tests show that this is a regular "Not Found" `http.Error()`, rather than a `panic` as I originally thought. 

I think we'll need to move `go/dhcp/` into `go/caddy/dhcp` in order to offload the error handling to a separate middleware layer. This is beyond me - for completion within a short time frame. It may be possible to skip the middleware and use more basic handlers, but it's hard for me to tell in advance if this will work (or not).

I'll defer from getting into this right now. Please let me know if you still want me to go ahead with this.

**Comment by julsemaan** [comment]
@satkunas 

No need to move to the caddy directory.

I think server errors can stay as is for now, what we would need to fix is:
- [x] Have interface not found return a standard Unified API error
- [x] Fix the pfstats logging so it concatenates the strings together instead of passing multiple arguments to the logger (`log.LoggerWContext(ctx).Error("API error", err.Error())` -> `log.LoggerWContext(ctx).Error("API error: " + err.Error())`)

**Comment by satkunas** [comment]
@julsemaan 2nd point addressed with https://github.com/inverse-inc/packetfence/pull/3113/commits/a3305fa67e19fccb42a1082a9cba449c26efcda8

**Comment by satkunas** [comment]
@julsemaan the following needs to be done within `go/dhcp/`

- [ ] Have interface not found return a standard Unified API error

Can we get @fdurand to handle this one?

**Comment by julsemaan** [comment]
I think he has his fair share of stuff to do, he can confirm that.

It would be handy to have you fix it

**Comment by fdurand** [comment]
Should be ok now.
I return : 404 {"message": "Interface not found"}
