### ISSUE TITLE
Dashboard: weird alerts

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3126]
Getting some alerts that seem to be meaningless unless you're some kind of Jedi:
![image](https://user-images.githubusercontent.com/3857942/38807456-a6bc554a-414a-11e8-9c34-8f054d7374b1.png)

**Comment by cgx** [comment]
Those are the alerts related to the monitored authentication sources using pfstats. We need to find out how to associated relevant information to the alerts.

**Comment by fdurand** [comment]
I tried to change the alarm.family to something more revelant but it looks that the alert is not associated to the chart.
An alternative should be to use alarm.info instead. @julsemaan  @cgx  what do you think ?

**Comment by julsemaan** [comment]
@fdurand 

This all sounds like chinese to me, maybe @atran-inverse can decode it :)

Jokes aside, I still have no clue what that means

**Comment by cgx** [comment]
@fdurand do you mean that this would a limitation of the statsd [go library](https://godoc.org/gopkg.in/alexcesaro/statsd.v2)?

**Comment by fdurand** [comment]
No there is no limitation but when you create a alert in netdata you can define "familly: ...".
Right now it's "familly: *" but when i change it to something more detailled the alert is not joigned to the chart, so the alert is never triggered.

So per example, instead of "swap" it will be "the swap memory used, as a percentage of the system RAM"
And instead of "gauge" or 'timers" it will be "AD source Availability" or whatever we defined.

**Comment by cgx** [comment]
Improved with f7c1a1e.
