### ISSUE TITLE
configurator : rewriting of /etc/sysconfig/network-scripts/ifcfg-*

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3426]
In `packetfence-8.1.9-0.201807170000.el7.noarch` with CentOS 7.5.1804, I notice that when you configure an existing network interface (e.g. `ens160`) from configurator, PacketFence will completely replace content of `/etc/sysconfig/network-scripts/ifcfg-ens160`. When it do that, `HWADDR` directive is empty : 

```console

[root@PacketFence-ZEN ~]# cat /etc/sysconfig/network-scripts/ifcfg-ens160
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=dhcp
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens160
UUID=27f5f975-88f0-444d-a2f0-2e0a039810d3
DEVICE=ens160
ONBOOT=yes
HWADDR=08:00:27:9b:81:77

### Configurator (step2)

[root@PacketFence-ZEN ~]# cat /etc/sysconfig/network-scripts/ifcfg-ens160
DEVICE=ens160
HWADDR=
ONBOOT=yes
BOOTPROTO=static
NM_CONTROLLED=no
IPADDR=10.0.2.15
NETMASK=255.255.255.0

```
PacketFence should write `HWADDR` of `ens160` in file.

Indeed, if you have renamed your interface with `/etc/sysconfig/network-scripts/ifcfg-ens160` file (see 1. in [Red Hat's doc](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-understanding_the_device_renaming_procedure)), you could loss access to your system after rebooting because CentOS could rename your interface `ens160`.

**Comment by nqb** [comment]
#2845

**Comment by nqb** [comment]
https://github.com/inverse-inc/packetfence/blob/64a2f1ccbc3a3ea2b246ed9fe1fd95d1cebd7f05/html/pfappserver/lib/pfappserver/Model/Config/System.pm

**Comment by tony3142** [comment]
It would appear that my experience is covered by this #3426.

I am running the latest release of CentOS 7.6 minimal install with the 
"packetfence-release-1.2-7.el7.noarch.rpm" installed on the CentOS 7.6.

I wanted to use the old naming convention for interfaces ifcfg-ethX instead of the default in CentOS 7.x

Here is what I have found:

I have discovered that there is an issue using the "old" naming
convention method with PacketFence and Centos 7.6, as shown in the
link below.

https://sites.google.com/site/syscookbook/rhel/rhel-network-interface-rename-rhel7

PF strips the MAC address from the ifcfg-ethX when saving changes.
Centos relies on the MAC address being in the ifcfg-ethX file.
Example of PF generated ifcfg-eth0:

/etc/sysconfig/network-scripts/ifcfg-eth0

DEVICE=eth0
HWADDR=
ONBOOT=yes
BOOTPROTO=static
NM_CONTROLLED=no
IPADDR=192.168.1.200
NETMASK=255.255.255.0

This is what it should look like

DEVICE=eth0
NAME=eth0
HWADDR=ab:cd:ef:12:34:56
ONBOOT=yes
BOOTPROTO=static
NM_CONTROLLED=no
IPADDR=192.168.1.200
NETMASK=255.255.255.0

The second listing has the MAC address and the NAME. According to the
documentation I have found, CentOS7/RHEL7 requires the HWADDR and NAME
to be populated.

Centos7 uses "/etc/udev/rules.d/70-persistant-net.rules" to set up the
interfaces with the correct name.

Example for the above scenario:

SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*",
ATTR{address}=="ab:cd:ef:12:34:56", ATTR{type}=="1", KERNEL=="eth*",
NAME="eth0"

When you pass "net.ifnames=0" to the kernel during boot, and have
"/etc/udev/rules.d/70-persistant-net.rules" correctly populated, the
system will correctly assign the interfaces so that you get consistent
assignment of IP addresses to the correct physical ports.

If you boot Centos7 after PF has saved the configuration, the system
comes back with the "normal" em1, em2 etc. names and creates files
like ifcfg-em1
This effectively disables PF.

Is there an easy way of getting PF to not strip the MAC address and
NAME from the ifcfg-eth0 file? I have not been able to find anywhere
in the GUI to add a MAC address.

Is there somewhere I can make a mod to fix this? Not sure if many
people use the "old" way but there are a few benefits in doing so in
certain circumstances.
Maybe this could be added in an update or a patch...

Tony

**Comment by nqb** [comment]
> Is there an easy way of getting PF to not strip the MAC address and
> NAME from the ifcfg-eth0 file? I have not been able to find anywhere
> in the GUI to add a MAC address.

Don't use the configurator to configure your network cards. Only use pf.conf and your network scripts.

**Comment by nqb** [comment]
Closing this in favor of #5659
