### ISSUE TITLE
VLAN filters : incomplete docs

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3494]
Extract from `vlan_filters.conf.example`:
```
# Rule(s)/Condition(s)
# --------------------
# Structure example of a rule/condition
# [NAMEOFRULE]
# filter = FILTER
# operator = OPERATOR
# value = VALUE

[..]

# Attribute can be:
# - for connection_type
#     Wireless-802.11-EAP
#     Wireless-802.11-NoEAP
#     Ethernet-EAP
#     Ethernet-NoEAP
#     SNMP-Traps
#     Inline
#     WIRED_MAC_AUTH
# - for the radius_request
#     All the attributes you can have in the RADIUS request (run FreeRADIUS in debug mode to see these attributes)

[..]

#[EAPTLS]
#filter = radius_request
#attribute = EAP-Type
#operator = is
#value = EAP-TLS
```

Two remarks:
- `attribute` directive is missing in `[NAMEOFRULE]` section
- `Attribute can be` doesn't apply for `connection_type`, we should use `Value`

**Comment by julsemaan** [comment]
I think attribute isn't even supported anymore, that would be just an old example

I believe the new syntax would be:
```
#[EAPTLS]
filter = radius_request.EAP-Type
operator = is
value = EAP-TLS
```

@jrouzierinverse or @fdurand can confirm

**Comment by jrouzierinverse** [comment]
It is still supported

**Comment by jrouzierinverse** [comment]
It is appended to the filter

**Comment by nqb** [comment]
If there is also a new syntax, we need to add docs on that point.

**Comment by julsemaan** [comment]
The "new" syntax is there since version 5.x I think. Although I'm favorable in keeping support for it for backwards compatibility, examples shouldn't use the old syntax anymore.

The new syntax is in use in all the examples:
https://github.com/inverse-inc/packetfence/blob/devel/conf/vlan_filters.conf.example#L221
https://github.com/inverse-inc/packetfence/blob/devel/conf/vlan_filters.conf.example#L255

And the filters are properly documented using the new syntax:
https://github.com/inverse-inc/packetfence/blob/devel/conf/vlan_filters.conf.example#L29

So I think just fixing the example to use the right syntax should be plenty for this specific case.

Also, if you feel like improving the example file with additional information on the new syntax, that would be good as well.
