### ISSUE TITLE
alerting emailaddr : unexpected behavior with more than one address

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3578]
The option `alerting.emailaddr` in `pf.conf` is designed for only one address but you can specify more than one, separated by comma without warnings. However, additional email addresses will never be notify.

In my opinion, we have two solutions:
1. disallow additional address in this field
1. permit additional address in this field

I'm not sure to have the big picture to choice between 1 and 2. What's your opinion ?

**Comment by julsemaan** [comment]
They will actually get notified, otherwise that feature is broken, but it used to notify multiple admins

**Comment by julsemaan** [comment]
Marking this as a +1 since that might be more a bug than a missing feature

**Comment by nqb** [comment]
Ok so that feature is broken.

Steps to reproduce:
- set emailaddr like this : `emailaddr=example1@domain.com,example2@domain.com` in `pf.conf`
- reload config : `/usr/local/pf/bin/pfcmd configreload hard`
- try to send an e-mail through `pfmailer` function:
```perl
perl -I/usr/local/pf/lib -Mpf::config::util -e 'pf::config::util::pfmailer(('subject' => "pfmailer test", 'message' => "Test"))'
```

Actual results:
- example1@domain.com will receive an e-mail
- example2@domain.com will **not** receive an e-mail even if it is mentioned in email header
- `keepalived` will fail sending email

If I remove `split` function at:
https://github.com/inverse-inc/packetfence/blob/33eb43ab3a53490379aaff3df66c27ed41cb029d/lib/pf/config/util.pm#L147
by:
```perl
my @to = $Config{'alerting'}{'emailaddr'}; 
```
I can send e-mail through `pfmailer` but `keepalived` template need to be adjust.

Moreover, some pf components use `send_email` function to send e-mails. I'm not sure that function support multiple addresses too. We need to do same things for each function.

**Comment by veedubbs** [comment]
I might not know enough about the software, but can you confirm a couple of things:

- This recipient field is _unrelated_ to monit, because monit has its own config.
- This recipient field is related to who gets the 'maintenance patch available' email?
- This recipient field is related to who gets Violation emails?

In my setup I have two addresses in that field.  We both receive the 'patch available' email but only I receive the email for Violations (we have been testing with the 'Lost or Stolen' violation).  I am the first email address in the field and we separated it by comma.

Weirdly enough, the email I receive shows us both as recipients:

![pf-1](https://user-images.githubusercontent.com/382007/44810240-c0a0ae00-ab96-11e8-94b3-e2abb0b79e8a.JPG)

But according to my Google logs it only got sent to me:

![pf-2](https://user-images.githubusercontent.com/382007/44810261-d910c880-ab96-11e8-8407-8c072b03f897.JPG)

Hope this helps!

**Comment by veedubbs** [comment]
Ultimately, if only one recipient is allowed (which is fine), I would just enter the email address to our ticketing system and let PF create tickets for things like violations, etc...

**Comment by julsemaan** [comment]
@veedubbs 

> This recipient field is unrelated to monit, because monit has its own config.

   100% right

> This recipient field is related to who gets the 'maintenance patch available' email?

   No, that is also the monit configuration

> This recipient field is related to who gets Violation emails?

   Yes

**Comment by julsemaan** [comment]
Bottom line is, we should have the ability to put 2 emails (or 10, 100) and the email should be sent to all of them like it used to.

**Comment by julsemaan** [comment]
@nqb 

If you feel comfortable fixing this bug, then go ahead, I think the desired behavior has been determined, otherwise, we'll continue the discussion
