### ISSUE TITLE
pfperl-api doesn't handle mem-leaks correctly

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3599]
When actively using the API, it seems its generating a memory leak which isn't correctly handled by cycling the forked API workers when they reach a certain threshold (or have served a certain amount of requests)

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
88549 pf        20   0 2721340   2.2g   5188 S   0.0 14.3   3:59.26 pfperl-api
88547 pf        20   0 2775132   2.2g   5224 S   0.0 14.0   2:53.50 pfperl-api
```

**Comment by jrouzierinverse** [comment]
mojo does not have this built in I will see if I can make this +1 patch

**Comment by zhangjianing0424** [comment]
While this commit mitigates the issue of excessive memory consumption in pfperl-api caused by frequent REST requests, it does not address scenarios where individual requests carry large payloads. For instance, creating 2000 roles and subsequently configuring VLAN assignments for each role on switches can result in significant memory usage within a single request.
