### ISSUE TITLE
connection profile : hide sources when using root portal module

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3616]
When you a use a root portal module other than the default in a connection profile, the authentication sources defined are not used but they still appeared to the user. That can lead to misunderstanding.

In that case, it will be nice to hide the sources section or to refer to the root portal module in use.

**Comment by julsemaan** [comment]
Not sure how we can accurately do that since that would require to deeply inspect the modules that are in use since I could certainly just remove the default_login_policy from the default_registration_policy and that would prevent any internal sources from being used but not the other sources so the section would still be relevant. I can do this by modifying the default root portal module so referring to it won't give people much details.

What we could do is that if we detect that the portal module that is in use for the connection profile isn't the default one and isn't pristine (the root or one of its child modules has been modified) then we display an additional note beside the sources to let the user know that the sources *may* not be taken into consideration.

**Comment by nqb** [comment]
@julsemaan: second solution would be fine but we need **to emphasize** note label.

**Comment by jrouzierinverse** [comment]
Is this still an issue or should we close it?
