### ISSUE TITLE
sponsor guest registration: untranslated email

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3670]
To reproduce: Create a sponsor request by visiting captive portal with a web browser configured in French.

Actual result: Sponsor will receive an email with:
* subject in French (see #3669)
* content in English

Expected result: Sponsor should receive email with subject and content in French. 

Template contains I18n tags and chains are present in `conf/locale/fr/LC_MESSAGES/packetfence.po`

**Comment by nqb** [comment]
@jrouzierinverse: did you find something on this ?

**Comment by nqb** [comment]
BUMP

**Comment by jrouzierinverse** [comment]
We set the language to the configured Language in PacketFence advanced.language not the language of The browser for sponsor emails.

https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/activation.pm#L438

We need to decide on the proper behavior for which language to use when sending sponsor emails.

In my opinion it would be better to make sure that the language of the email is sent in the Language that is configured in PacketFence not in browser.
Because If I am visiting an office in Japan the person sponsoring my access should get an email in the language that is configured in PacketFence.
Not whatever happens to be configured in my browser.

**Comment by nqb** [comment]
For the record, code in #3698 fixes only bad translation for the subject.
