### ISSUE TITLE
Installation mysql root password

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3704]
A fresh packetfence installation produces the following output during the `yum install`, but the stdout message is quickly lost in the scrollback. It should be reiterated in the installation docs to act as a reminder for those who miss the message in stdout.

```
PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:

'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h localhost.localdomain password 'new-password'

Alternatively you can run:
'/usr/bin/mysql_secure_installation'
```

**Comment by nqb** [comment]
@satkunas,

For me, the configurator will do the job when you will be at the "Database" step.

**Comment by satkunas** [comment]
@nqb for me there's enough of a time window between the installation and configurator to be exploited. If the daemon is expected to be listening on 3306 it should be secured ASAP, as configuration could be days later.

**Comment by julsemaan** [comment]
@satkunas 

IMO, the configurator should be done when you install the machine, not days after.

It sounds like doubling the job and it could confuse people that are used to the current recipe since they won't be setting the password in the configurator but instead in the command line to then reference it in the configurator.

The configurator was actually put there to remove the need to use the command line while setting up PacketFence (for example, I could setup PF without touching the command line if I use the ZEN)

**Comment by jrouzierinverse** [comment]
Another option is on a fresh install is to only listen on the localhost.
As this will reduce the attack surface.

**Comment by satkunas** [comment]
A fresh install test confirms that before the configurator is run, mysql only listens on local unix socket, and doesn't listen via TCP.

This makes it a non-issue, thus I'm closing this issue now.
