### ISSUE TITLE
Docs - Custom Reports doesn't explain `type=builtin` directive

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#3743]
I copied over `conf/reports.conf.default` to `conf/report.conf`.

All defs in this file include a `type=builtin` directive. This directive is not explained in the docs: https://[packetfence-host]:1443/static/doc/PacketFence_Installation_Guide.html#_custom_reports

**Comment by julsemaan** [comment]
And BTW, don't copy conf/reports.conf.defaults to conf/report.conf

The non-default is an overlay on the defaults file so that we (PF team) can push changes to the default configuration across releases although users have changed the configuration. That way the overlay simply overloads what it needs to. 

Basically the same principle as pf.conf with pf.conf.defaults
