### ISSUE TITLE
Possibility to filter RADIUS accounting requests

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3773]
In some cases, it could be necessary to filter RADIUS accounting requests coming from network devices.

It will be nice if we can do it with your filter engines (VLAN filters, RADIUS filters, etc.).

**Comment by nqb** [comment]
@fdurand: maybe we can rely on what you start in #3753

**Comment by julsemaan** [comment]
#3753 doesn't have anything to do with RADIUS filters, IMO we better not iterate on this PR to add filtering into it and instead just start a new branch and PR

**Comment by fdurand** [comment]
It's already in my TODO list since i need that to proxy accounting request based on some attributes.
This will be done in https://github.com/inverse-inc/packetfence/pull/3278.
I will keep @jrouzierinverse to have a look to integrate the VLAN Filters (or other filters engine) with the radius accounting.
