### ISSUE TITLE
Too complex password prevent MariaDB to start

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3837]
In a cluster environment, if I a create a `pfcluster` user with `<;8C3Sn5Phj\,gv` as password, MariaDB will not start.

**Comment by julsemaan** [comment]
I think this is due to the fact that the xtrabackup sync strategy of Galera doesn't quote the passwords which in the past has caused issues with passwords containing spaces.

I'll modify the note in the clustering guide to instruct to use alphanumeric characters (A-Z a-z 0-9 without spaces) so that doesn't happen again
