### ISSUE TITLE
API GET /api/v1/token_info → add readonly_mode

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4209]
We need to return a boolean attribute (say, `readonly_mode`) in the response of `/token_info` (or another endpoint?) to get this [database status](https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/db.pm#L594-L598).

**Comment by julsemaan** [comment]
Probably another endpoint because the api-frontend doesn't have direct access to this logic

We could create a new API endpoint /system_summary that would provide this info along with other good stuff like the hostname

If that sounds good, I could take care of this so @jrouzierinverse can focus on other issues

**Comment by cgx** [comment]
Or we return this information from `/api/v1/service/mariadb/status`?

**Comment by julsemaan** [comment]
That endpoint doesn't exist AFAIK since mariadb is not a service managed by pfcmd and the read-only mode is not directly related to the local MariaDB service since the user might be running an external MariaDB Galera cluster that is independant of PF but the checks would still work

**Comment by cgx** [comment]
Go for `/system_summary`. Let's include the installed PacketFence version in the response. See #4227 .
