### ISSUE TITLE
API OPTIONS /api/v1/system_summary → token required or not?

### ISSUE THREAD

**Issue by cgx** [inverse-inc/packetfence#4336]
For discussion.

I propose to make `/system_summary` accessible without a token.

**Comment by nqb** [comment]
I'm not sure it's a best practice because anybody can get PF version without logging. An attacker can run specific attacks based on this information.

**Comment by extrafu** [comment]
I don't think that is an issue - security by obfuscation is always quite bad.

**Comment by julsemaan** [comment]
The only thing that could be bad with this would be the read-only status of the system (MariaDB in read-only) and exposing this to unauthenticated users.

But then again, if you would access the captive-portal, you would be able to know if the system is in that state so that probably won't be an issue.

We just have to be careful as to what we put into this API endpoint

**Comment by nqb** [comment]
What is the interest of exposing this API endpoint without a token ?

**Comment by cgx** [comment]
@nqb Having the version and read-only mode accessible on the login page.

**Comment by nqb** [comment]
Ok @cgx. Who need this information ?
If an admin wants to get PF version, he just needs to log in.

**Comment by jrouzierinverse** [comment]
We could cherry-pick what information we display depending if they are logged in or out.
However I am not sure that we send down the token information to the pfperl-api for paths that do not require a token @julsemaan can you verify this?

**Comment by julsemaan** [comment]
Right now the API frontend assumes that all requests have to be authenticated before going to any API backend.

Meaning pfperl-api should currently assume all requests are authenticated

The API frontend needs to be adjusted to bypass authentication on specific backend paths

Now, when I'll have this bypassing the auth, the X-PacketFence-Username will not be populated so that can be used to flag requests that are authenticated or not in the backend

Works for everyone ?

**Comment by jrouzierinverse** [comment]
That sounds good.
@cgx is just readonly_mode need for unauthenticated request or anything else?

**Comment by cgx** [comment]
FYI -- `/api/v1/translation/<locale>` doesn't require authentication.

Let's keep `/api/v1/system_summary` for authenticated users only.
