### ISSUE TITLE
Missing Rapid7 tab in new admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4358]
In the node details, the Rapid7 tab is missing in the new admin

**Comment by julsemaan** [comment]
@satkunas, can we aim to make this a thing for 9.1 ?
This is a regression from pre-9.0

**Comment by nqb** [comment]
Hello,

Is it something that has been forgotten since 9.1 ?

**Comment by julsemaan** [comment]
Yes definitely

**Comment by extrafu** [comment]
API endpoints are missing. @jrouzierinverse will need to add them first.

**Comment by jrouzierinverse** [comment]
The endpoint is there is the backend  
However, I am not sure the frontend is there. Move this to 10.2?

**Comment by satkunas** [comment]
Rapid7 was deprecated when we released version 9 because we didn't have any Rapid7 configuration to test against, and our customers who use it were unresponsive in our requests for assistance. Because of this we agreed the regression was acceptable - due to the lack of choice.

Keep bumping the release version until we can get a working environment to test with.

**Comment by satkunas** [comment]
Bumping release to revisit.

**Comment by julsemaan** [comment]
Tired of pushing this forward, closing
