### ISSUE TITLE
v9-gui: Cluster state + cluster service state not displaying

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4403]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/5261214/57404221-74881d80-71a9-11e9-8db5-1bfd31f7ab09.png">

**Comment by cgx** [comment]
Instead of having a single API endpoint to fetch the services status of all the cluster members, the endpoint should expect a server as argument. Ex:

`/api/v1/cluster/<server_ip>/services`

or

`/api/v1/services/<server_ip>`

This way the frontend would be faster by querying all the cluster members at the same time.
