### ISSUE TITLE
Updating role name "breaks" switches.conf configuration

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#441]
When a role is created, and a VLAN value is assigned to that role for a switch, updating that node role will simply remove the field from the switch role list (but will keep it in switches.conf) and replace it with the new role with an empty value.

How to reproduce:
- Create a role
- Go into a switch and assign a VLAN for that role
- Rename the role
- Go back in the switch config.

Expected behavior:
The role name should be changed... Otherwise, you will have to go through all the config and replicate the change.

**Comment by dwlfrth** [comment]
I think this should be addressed in v5... or earliest possible...

**Comment by jrouzierinverse** [comment]
Renaming roles will also break pf::profile::filter::node_role or anything else that uses that role name instead of the id.
We should look into storing the role_id instead of the name in switches.conf and other places.
That would be a better solution over all then having to rewrite configs every single time.
Or we do not allow renaming of roles since we know it will break things.

**Comment by extrafu** [comment]
Does deleting a role works as expected?

If so, let's prevent for now (v5) the renaming of a role.

**Comment by jrouzierinverse** [comment]
Deleting a role according to Julien is better.
Also this is not a new bug so I would say let us take care of it in the next release when we move switches into the db.

**Comment by extrafu** [comment]
Let's at least make sure we can't rename a role.

**Comment by jrouzierinverse** [comment]
ok
