### ISSUE TITLE
Add CoA support for Unifi switch modules

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4573]
**Describe the solution you'd like**
Unify [now supports CoA](https://community.ubnt.com/t5/UniFi-Feature-Requests/Implement-802-1x-Change-of-Authoirzation-CoA-support/idc-p/2793600/highlight/true#M19511), we should support CoA for Unifi switch modules.

**Comment by nqb** [comment]
@theonemcdonald, could you confirm CoA is supported on Unifi Controller too ?

**Comment by rcmcdonald91** [comment]
@nqb 

Yes, it’s available in the Controller and the firmware. You can find the CoA settings per wireless network configuration in UniFi.

Controller: >5.12
Firmware: >4.0.54 (I think)

![COA](https://user-images.githubusercontent.com/3102039/65342861-a1a9fb00-dba1-11e9-8b5a-65c4f3ce6857.png)

**Comment by fdurand** [comment]
We will wait until 5.12 is released, there is no way to download it.

**Comment by rcmcdonald91** [comment]
https://community.ui.com/releases/UniFi-Network-Controller-5-12-5/6e656b4e-5406-44c3-a56c-a4637ae7a6b3

You will need a Ubiquiti account and access to the beta channel (both are free and easy to sign-up for).

**Comment by fdurand** [comment]
Thanks, i have it.

**Comment by fdurand** [comment]
Just an update, i am not able to make it work.
In the access point they use a kind of CoA proxy who send the request to the correct instance of hostapd.
Per example the normal port is 3799 and the hostapd instance for the ssid bob is 3800 and obo is 3801, so the "proxy" is suppose to test the bssid value and forward to the port 3800 or 3801.
The issue is that in the configuration file the variable $bssid is not translated to the correct value, so the proxy doesn't work.

**Comment by nqb** [comment]
@fdurand, could you open an issue upstream ?

**Comment by rcmcdonald91** [comment]
https://community.ui.com/questions/Is-802-1X-Change-of-Authorization-CoA-support-still-on-the-road-map/caec9c47-4067-4fb2-8f72-3be316cc236a#answer/d9f23ee9-7507-4ef2-ad59-0ba3ab1efd5b

**Comment by nqb** [comment]
@theonemcdonald, even after being logged in, I'm not able to reach this web page.

**Comment by rcmcdonald91** [comment]
You need to have beta access.

https://account.ui.com/earlyaccess

**Comment by fdurand** [comment]
Exactly the same issue i have.

**Comment by nqb** [comment]
Moving to v10.1
