### ISSUE TITLE
webadmin: value unsupported for access duration

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4726]
Configuring following access duration is not possible in new webadmin: `3MF+0D`, still possible in old webadmin.

**To Reproduce**
1. Try to configure an access duration (relative to the beginning of the day or the period) with `0` as value for additional duration

**Screenshot**
![Screenshot from 2019-08-19 15-52-06](https://user-images.githubusercontent.com/10830260/63270907-50a0a180-c299-11e9-9524-feb00264d5a1.png)

**Expected behavior**
Choice accepted.

**Comment by satkunas** [comment]
@nqb appending `+0x` does nothing to change the date, so it's not required to retain it since it's useless. Just because it's "**still possible in old webadmin**" - this doesn't make it right. Here's some examples using the perl backend to parse a couple different durations:

```
3MF = 2019-12-09 23:00:00
3MF+0D = 2019-12-09 23:00:00
3MF+1D = 2019-12-10 23:00:00
3MR = 2019-11-30 23:00:00
3MR+0D = 2019-11-30 23:00:00
3MR-0D = 2019-11-30 23:00:00
```
I would need to refactor the serialization and deserialization in order to support this, which seems more trouble than its worth.

https://github.com/inverse-inc/packetfence/blob/703fcb98942d521164eca457a91e205c28f33eaa/html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAccessDuration.js#L10

https://github.com/inverse-inc/packetfence/blob/703fcb98942d521164eca457a91e205c28f33eaa/html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAccessDuration.js#L30

Re-assigning tags.
