### ISSUE TITLE
Web Admin - Custom Reports generates many 404s while loading undefined user preferences.

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4895]
**Describe the bug**
Load the Reports section in the web admin. Note many 404's in the network debug.

A 404 is generated for each preference that is loaded but does not exist.

We should leverage using the collection @ `/api/v1/preferences`

@jrouzierinverse Currently the `/api/v1/preferences` is too verbose. It currently includes both the key and the value. It should be modified and scaled back to only list the keys to reduce the page size. 

Afterwards the front-end should use this collection endpoint to determine which preferences exist without having to probe each key for a 404.

**Comment by jrouzierinverse** [comment]
Part of the issue is the endpoint does not use the standard CRUD interface.
So you cannot use search or select the fields you want to be returned.
As far as I can see the only thing it does it filters the preferences by the current_user.
@julsemaan is there anything else that should be taken into consideration when moving preferences to the standard CRUD interface.

**Comment by julsemaan** [comment]
@jrouzierinverse 

What you've described is what is specific to that endpoint

**Comment by jrouzierinverse** [comment]
So to confirm there is nothing else as far as you know to take into consideration when moving preferences to the standard CRUD interface.

**Comment by cgx** [comment]
We should overwrite the string in the [source translation](https://github.com/inverse-inc/packetfence/blob/devel/conf/I18N/api/en.po#L12938).
