### ISSUE TITLE
web admin: generated passwords doesn't always meet requirements

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4939]
I tried to generate a password with default parameters:
- 8 characters
- ABC
- 123
- abc

I noticed that sometimes password doesn't contain numbers.

**To Reproduce**
1. Generate a password several times when creating a user with default parameters

Password will not always contain number.

**Expected behavior**
Passwords should meet requirements.

**Comment by satkunas** [comment]
This seems like a non-issue to me. Because a password may contain A-Z, doesn't mean that all characters from A-Z must be included. It builds it by assembling a combined set from the selected subsets and picks from the combined set randomly, which doesn't guarantee that there will be at least one character from a desired subset. The same should be true for numbers. Otherwise, it wouldn't be able to generate any password less than 7 characters if all 7 subsets are selected.

**Comment by nqb** [comment]
I agree with your explanation but it's not intuitive to see a box `123` checked to have a string that doesn't contain number at end.
