### ISSUE TITLE
Bypass role/vlan for specified time

### ISSUE THREAD

**Issue by chrkoe** [inverse-inc/packetfence#4977]
When you have some clients which needs a bypass vlan, you set the role/vlan and forgot about changing back.

It would be nice if you can add an option to set an "End date/time" for the bypass function.
e.g.:
role: "static"
bypass role: "dynamic"
bypass ends: "2019-29-11 03:00 pm"

And then you have to handle that date/time:
1. Wait for the next authentication request and remove the bypass vlan/role.
or
2. At that time remove the bypass vlan/role and start an reevalution of the device.

Imho this should be a must have for bypass role/vlan. Why would you set it as a bypass, if you won't change it back?

How do you think about that? Is it possible to add this to feature releases? I would be happy if so. :wink:

**Comment by julsemaan** [comment]
This isn't the intended usage of the bypass role and the bypass VLAN.

These are made to set roles for life in order to be able to ignore any dynamically assigned role when performing authentication of the user actively connected on the device (through the portal or through 802.1x) which would make the device belong in the role of the user instead of the role of the device itself.

With that in mind, a bypass role/VLAN is made to be set and never changed back. A good example would be a school that owns Chromebooks that should always go into the Chromebook role. They still want to authenticate students on these devices on the portal but not use the role of the student for the RADIUS reply.

Since the feature intended usage is what I described above, we don't really see a need of supporting what you are describing

**Comment by Venice-89** [comment]
> Since the feature intended usage is what I described above, we don't really see a need of supporting > what you are describing

Even it's not the intended usage, it would be a great extension for that feature and would not touch the situation you described ;) 

**Following situation:**
You have several clients which are automaticaly registered in a role which is not permited to acces the internet (802.1x machine auth)
But now, one client must have internet access for 2 Hours (Maintenance from vendor for example).
Right now you can set a bypass role and after 2 hours you remove the bypass role again ... or maybe you forgot it and the client stays in the wrong vlan forever, which can cause securty issues. 

In any case, it's more work to set a role manually and remove it after the specific time.
