### ISSUE TITLE
web admin: forbid actions without "Read" privilege in Admin roles menu

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4989]
Currently, you can create admin roles without "Read" privilege. For example, an admin role with only a "Node - Create" privilege. If you try to log on PF web admin with a user assigned to this role, your web browser freezes. In log you can see something:
```
Dec  6 15:17:44 pfcen7stable httpd_admin: httpd.admin(19433) ERROR: [mac:unknown] One of the following roles are not defined properly 'Role-1' (pfappserver::PacketFence::Controller::Admin::login) 
```

**To Reproduce**
1. Create an admin role called `Role-1`
   * Actions: Nodes - Create
1. Create a user `foo` and assign `Role-1` as access level
1. Log in as `foo` user

**Expected behavior**
Web admin should disallow this action.

**Comment by jrouzierinverse** [comment]
In order to log into the admin you must have certain permissions.
We could add NODES_CREATE permission to the login group.
However, does it make sense?

Here is the list of permissions.

SERVICES_READ
REPORTS_READ
USERS_READ
NODES_READ
CONFIGURATION_MAIN_READ
CONNECTION_PROFILES_READ
PROVISIONING_READ
ADMIN_ROLES_READ
INTERFACES_READ
SWITCHES_READ
FLOATING_DEVICES_READ
USERS_ROLES_READ
USERS_SOURCES_READ
SECURITY_EVENTS_READ
FINGERPRINTS_READ
MAC_READ
FINGERBANK_READ
FIREWALL_SSO_READ
REALM_READ
DOMAIN_READ
SCAN_READ
WMI_READ PKI_PROVIDER_READ
WRIX_READ
FILTERS_READ
PORTAL_MODULE_READ
USERS_READ_SPONSORED
AUDITING_READ
SELF_SERVICE_READ

**Comment by nqb** [comment]
> In order to log into the admin you must have certain permissions.

In that case, when you create an admin role that will be used to connect to web admin, we should ensure these permissions are defined.
