### ISSUE TITLE
css per portal profile

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#507]
Add a way to have a style.css file per portal profile

**Comment by cgx** [comment]
My suggestion: be more ambitious and allow to manage/edit any number of static files for each portal profile. The challenge is probably to configure Apache to serve those files.

**Comment by uow-dmurrell** [comment]
I've run into a probably related problem: images don't seem to be per profile either (this is on pf 4.7). 

To modify the default image for a custom portal, I've had to put it in /usr/local/pf/html/captive-portal/content/images rather than /usr/local/pf/html/captive-portal/profile-templates/customportalname/static/images. 

This may be a configuration problem on my part though.

**Comment by cgx** [comment]
@uow-dmurrell This is exactly the problem I would like to see fixed. All static files of all profiles must currently reside in the `content` directory.

**Comment by julsemaan** [comment]
We can by editing layout.html per portal profile and point it to a specific CSS file
