### ISSUE TITLE
Unable to sort internal authentication sources

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5127]
**Describe the bug**
If you try to change the sort order of the authentication sources via the new admin, it doesn't work.
The API call made by the frontend looks legit, seems like a backend API issue.

**To Reproduce**
1. Have multiple internal authentication sources
2. Attempt to reorder them
3. Refresh the page
4. Sources still ordered the way they were before the change

**Comment by jrouzierinverse** [comment]
Can you check if it was reordered in the config?

**Comment by jrouzierinverse** [comment]
I wonder if this is a cache issue

**Comment by jrouzierinverse** [comment]
I added a test in commit a1183876ecae5dab6fdb261199d15d1beb84e498 this is on the front end.

**Comment by satkunas** [comment]
Sorting is currently done using a defined key `id`. 

`/api/v1/config/sources?sort=id&fields=id,description,type,class`

@jrouzierinverse we may require a virtual column named something like `sort` or `order` that I can define in the API request rather than by `id`.

`/api/v1/config/sources?sort=sort&fields=id,description,type,class,sort`
