### ISSUE TITLE
Web admin: display switch template when editing a switch/switch group

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5167]
**Is your feature request related to a problem? Please describe.**
When you select a switch template on a switch or switch group, you want to check content of switch template. It could be nice to have a way to view switch template at this step without having to go in Switch Templates menu.

**Describe the solution you'd like**
A link on switch template name or next to switch template name to display switch template.

**Describe alternatives you've considered**
Open a new windows at foreground with switch template configuration.

**Comment by satkunas** [comment]
Currently switch template identifiers (ID) are open free-form text, thus there is now way to join a switch/switch-group to a template. 

In order to join them without error, we'll need to modify the Switch Template Identifier so the user must choose a distinct ID from a list of existing switch/switch-groups.

**Comment by jrouzierinverse** [comment]
We could add in the meta for the type if it is a template.

**Comment by jrouzierinverse** [comment]
In OPTIONS .meta.type.allowed[0].options[0].is_template can be used to know you are dealing with a template.
