### ISSUE TITLE
Changing the timezone in the admin doesn't change it on the system

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5205]
**Describe the bug**
Changing the timezone in the admin doesn't actually change it on the OS so you end up with a timezone being used by MySQL and another timezone being used by a part of the PF code. These should be made consistent

**To Reproduce**
1. Change timezone in the admin to something else than the one of the OS

**Comment by nqb** [comment]
Reopening issue because it doesn't work on Debian. `sudoers` file has not being updated for Debian.

**Comment by erSitzt** [comment]
I still have an issue on debian with regard to the timezone

i get
`WARNING: The timezone is being changed from /usr/share/zoneinfo/Europe/Berlin to Europe/Berlin on the system. It is advised to reboot the server so that all services start with the correct timezone.`

I think its related to the regex not working
`$lt =~ s/..\/usr\/share\/zoneinfo\///g;`

if i print out `$lt` its value is `/usr/share/zoneinfo/Europe/Berlin`

changing it to ``$lt =~ s/\/usr\/share\/zoneinfo\///g;`` works

This is a clean 1-day old fresh install btw ( both debian 9 and pf) if it helps..

**Comment by nqb** [comment]
Hello @erSitzt,

I'm able to reproduce your issue. Could you opened a dedicated one ?

**Comment by erSitzt** [comment]
Sure 
#5595
