### ISSUE TITLE
It shouldn't be mandatory to configure registration + isolation in configurator

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#522]
We should have a third mode (could be Web-auth) that doesn't make it mandatory to have registration and isolation interfaces.

**Comment by dwlfrth** [comment]
I think it should be an 'advanced' mode more than a third option.
From my point of view, configurator should be as easy as possible since it is used to guide end users and introducing a third choice can lead to "confusion".
That new 'advanced' mode could be use to use the configuration without any kind of limitation.

**Comment by julsemaan** [comment]
Agreed but a pure Web-auth guide would be worth to have IMO.

I think the advanced mode would be a good thing to have too. In our current code base it seems like it will create messy code though but we'll have to look into it

**Comment by julsemaan** [comment]
fixed by the portal interface type
