### ISSUE TITLE
403 Unauthorized access errors in PF 9.3

### ISSUE THREAD

**Issue by chencairong** [inverse-inc/packetfence#5256]
**Describe the bug**
After login with user who belongs to ‘User Manager’ role there are many 403 Unauthorized errors.

**To Reproduce**
1. Go to 'Users'.
2. Create user 'test' with access level 'User Manager'. 
3. Save.
4. Go to Login page use 2 created user 'test'.
5. Go to 'Users' -> 'Create'.
6. See the error
 
**Screenshots**
![image](https://user-images.githubusercontent.com/8074797/77816009-534e5980-70fa-11ea-9198-0f09eeca7d60.png)

**Expected behavior**
No 403 errors in the page.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome

**Additional context**
adminroles.conf
```
[Node Manager]
actions=NODES_READ,NODES_CREATE,NODES_UPDATE,NODES_DELETE,SECURITY_EVENTS_READ,SWITCHES_READ,DHCP_OPTION_82_READ
description=Nodes management

[User Manager]
actions=USERS_CREATE,USERS_DELETE,USERS_READ,USERS_UPDATE,USERS_SET_ROLE,USERS_SET_ACCESS_DURATION,USERS_SET_UNREG_DATE,USERS_SET_TIME_BALANCE,USERS_SET_BANDWIDTH_BALANCE,USERS_SET_ACCESS_LEVEL,USERS_MARK_AS_SPONSOR,USERS_CREATE_MULTIPLE
description=Users management

[Security Event Manager]
description=Security Events managements
actions=SECURITY_EVENTS_READ,SECURITY_EVENTS_CREATE,SECURITY_EVENTS_UPDATE,SECURITY_EVENTS_DELETE,USERS_READ,NODES_READ
```

**Comment by nqb** [comment]
On a 9.3 setup with maintenance patches applied, I'm able to reproduce this issue. However, it seems necessary to refresh browser cache when you log in as user "test" to see error messages. Features are not affected, only error messages displayed.

No more error messages if you add missing rights to User Manager role but it gives read access to other Configuration and Nodes menus which is not what you want.

**Comment by chencairong** [comment]
Thank you for your explanation!, @nqb

**Comment by nqb** [comment]
`NODES_READ` error message is caused by an API call to `/api/v1/node_categories` after login. 

If I had:
- `USERS_SET_TENANT_ID`
- `SYSTEM_READ`

to User manager admin role, only two errors messages left when creating an user:

- `Unauthorized access, lacking the CONFIGURATION_MAIN_READ administrative role` when calling `/api/v1/config/admin_roles`
- `Unauthorized access, lacking the ADMIN_ROLES_READ administrative role` when calling `/api/v1/config/base/guests_admin_registration`

However, these two API calls doesn't seems necessary because I see two other API calls that provide needed information:
-  `/api/v1/current_user/allowed_user_access_levels`
- `/api/v1/current_user/allowed_user_access_durations`

@satkunas, it is something you can adjust on the frontend ?

Regarding missing privileges for User Manager, I can add them to default User Manager admin role. `SYSTEM_READ` privilege can certainly be added to Security Events Manager and Node Manager admin roles.

**Comment by chencairong** [comment]
Hi, @nqb If i understand API calling correctly, there is one API can fetch all privileges of login user. it's `GET /api/v1/token_info`, so can frontend check privileges before send api to backend? for example, all privileges of ‘User Manager’ role are:
`{
"item": {
"admin_actions": [
"USERS_CREATE_MULTIPLE",
"USERS_SET_TIME_BALANCE",
"USERS_SET_BANDWIDTH_BALANCE",
"USERS_READ",
"USERS_SET_ACCESS_DURATION",
"USERS_SET_ACCESS_LEVEL",
"USERS_CREATE",
"USERS_SET_ROLE",
"USERS_SET_UNREG_DATE",
"USERS_UPDATE",
"USERS_MARK_AS_SPONSOR",
"USERS_DELETE"
],
"admin_roles": [
"User Manager"
],
"tenant_id": 0,
"username": "test",
"expires_at": "2020-03-20T12:38:17.347600622Z"
}
}`

**Comment by nqb** [comment]
@satkunas and @jrouzierinverse, what's your point of view on this issue ?

**Comment by jrouzierinverse** [comment]
This is an issue of the frontend asking for resources the user does not have access to.

**Comment by satkunas** [comment]
I'll add some checks in the front-end to suppress the requests if the required roles are not present.

**Comment by chencairong** [comment]
Thank you for all of your efforts.
