### ISSUE TITLE
Trying to type in the expiration date field of a user doesn't work

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5317]
**Describe the bug**
If you have an existing local user and you edit him, try to change manually the expiration date of the account (i.e. not using the calendar picker), then the moment you start typing in the field it puts the date in the calendar widget again overwriting what you were typing

**To Reproduce**
1. Create a local user
2. Edit it
3. Go in its actions tab
4. Try to type the date 2030-01-01 in the second field of the registration window

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Firefox
 - Version 74.0

**Comment by satkunas** [comment]
I'll need to spend some time on this one. There's some systemic problems using flatpickr, as it binds itself to the input element and attempts to be overly "helpful" without providing the neccesary event hooks for the special cases we need. The previous workarounds were implemented in order to allow an empty date (from another issue), which is now causing the issue described above. 

I'll attempt hide the default input element that flatpickr binds itself to, and add a secondary input element for the user that's completely detached from the flatpickr component - and implement a reactive proxy to pipe between the two inputs - in hopes that we can get it to accommodate all use cases. I'll attempt to address other weaknesses we have with the current component during the refactor.

**Comment by satkunas** [comment]
@julsemaan please retest with the latest changes

**Comment by julsemaan** [comment]
Works!
