### ISSUE TITLE
web admin: saved searchs didn't appear after a refresh

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5331]
**Describe the bug**
When you save a search, it's not possible to use it later.

**To Reproduce**
1. Save a search
2. Refresh your browser
3. Try to find your saved search

=> Search is not available.

**Expected behavior**
Saved search should appear.

**Additional context**
Creating a saved search works. All looks good from web browser console.

When I refresh my browser, I didn't see any API calls to endpoint related to saved searchs.

I wonder if recent changes to httpd.admin have break logic.

**Comment by satkunas** [comment]
@nqb saved search paths are being URL encoded. This is unexpected and I'm not sure when this issue was introduced:
 -  Much earlier when we implied URL encoding with all API requests.
 -  Recently when we switched from httpd-admin to haproxy-admin
 -  Recently due to some other backend change.

@jrouzierinverse adding URL encoding to perl fixes this issue. See the following patch which I'll defer to you to apply in order for you to ensure it's correct. Unless you think it was due to a misconfig in haproxy-admin.

```
diff --git a/lib/pf/UnifiedApi/Controller/Preferences.pm b/lib/pf/UnifiedApi/Controller/Preferences.pm
index ec69ac7..1bf29bf 100644
--- a/lib/pf/UnifiedApi/Controller/Preferences.pm
+++ b/lib/pf/UnifiedApi/Controller/Preferences.pm
@@ -19,6 +19,7 @@ use pf::I18N::pfappserver;
 use pf::constants;
 use pf::error qw(is_success is_error);
 use pf::dal::user_preference;
+use URI::Escape;
 
 =head2 list
 
@@ -137,7 +138,7 @@ sub replace {
 
     ($status, my $obj) = pf::dal::user_preference->find_or_create({
         pid => $username,
-        id => $preference_id,
+        id => uri_unescape($preference_id),
     });
 
     if (is_error($status)) {
```

**Comment by nqb** [comment]
I did a new test today on a 10.3 setup: same behavior.

Saved searches are lost after you refresh your web browser.

**Comment by nqb** [comment]
This issue is not present anymore on 11.1.0 (not tested on 11.0.0).

Now, I see that saved searches are stored under `user_preference` table per `pid` and can be managed directly under "Preferences" menu for each user.

@jrouzierinverse, two questions:
- Is `savedsearch`  table still necessary ?
- What do you want to do with this issue ?

**Comment by jrouzierinverse** [comment]
We should close this issue and remove the savedsearch table.
