### ISSUE TITLE
web admin: unable to preview HTML files on a connection profile

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5351]
**Describe the bug**
When you want to preview a HTML file of your connection profile, for example, `account.html`, you got `404 Site pfdeb9dev.lan:1443 is not served on this interface`
 
**To Reproduce**
1. Go in "Files" tab of any connection profile
2. Click on 'Preview'

**Expected behavior**
Should display preview of HTML file.

**Additional context**
If I try to edit `account.html` on `default` connection profile, my web browser try to reach https://pfdeb9dev.lan:1443/config/profile/default/preview/account.html

Similar to #5283

**Comment by lzammit** [comment]
On a cluster where .100 is the management VIP : 

![image](https://user-images.githubusercontent.com/5261214/79122491-c34d1880-7d65-11ea-9088-e72ea2d51a4d.png)

**Comment by fdurand** [comment]
This is part is handle by the old admin gui.
I will probably need to fix in the same way i did the portal_preview.

**Comment by fdurand** [comment]
We need an api endpoint to render the html file.

**Comment by satkunas** [comment]
API endpoint works, but is unusable. 

A special workaround is needed in order to render the markup in the browser without an actual HTTP GET from the browser, making the page static and unable to load external resources due to Browser security preventing unwanted XSS on a non-same-site-origin page.

```javascript
fetch(`data:text/html;base64,${base64EncodedTemplate}`).then(res => {
  Promise.resolve(res.blob()).then(blob => {
    const blobURL = URL.createObjectURL(blob)
    window.location = blobURL
  })
})
```

Result:

![Screenshot_20200414_155525](https://user-images.githubusercontent.com/3904468/79268213-6423fc80-7e68-11ea-8abe-8aedf07dd409.png)


**Rendering the markup on the page omits any GET and execution any external CSS or Javascript**, thus the final result is only a partial view.

I think we'll need to expose the templates via HTTP regardless.

**Comment by satkunas** [comment]
Stashing diff for my changes up until this point

[diff.zip](https://github.com/inverse-inc/packetfence/files/4477489/diff.zip)
