### ISSUE TITLE
Authentication::SAML: with_aup setting ignored on captive portal

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5476]
**Describe the bug**
If you want to display an AUP to your SAML users before they registered, you can't. By default, when you create an Authentication::SAML portal module, `with_aup` is enabled. However, when you preview captive portal, you are invited to directly click on SAML redirect link.

**To Reproduce**
1. Create a SAML source
2. Create a Root portal module
3. Create an Authentication::SAML portal module with default settings (`with_aup=1`)
4. Assign Authentication::SAML portal module to Root portal module created at step 2
5. Assign your Root portal module on your connection profile
6. Preview your connection profile

=> AUP is not displayed.

**Expected behavior**
AUP displayed before SAML redirect link.

**Comment by nqb** [comment]
In [html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SAML.pm](https://github.com/inverse-inc/packetfence/blob/b164e498dac38ef40c297791b173e6f47ff4b944/html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SAML.pm), there is no call to `prompt_fields` function.

**Comment by julsemaan** [comment]
As discussed in the private email thread, to prompt for fields while using SAML, we need to chain this with another module (like Null) and use "Fields to save".

As for the AUP, we need to honor it so that will be fixed

I will also take care of removing the fields that aren't honored from the SAML portal module form
