### ISSUE TITLE
portal preview: issue when testing OAuth or OpenID sources

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5504]
**Describe the bug**
When you try to preview a portal with an OAuth or an OpenID source from web admin, redirection are wrong

**To Reproduce**
1. Create following OpenID source:
```ini
[google]
create_local_account=no
client_secret=fakeapikey
password_length=8
access_token_path=https://accounts.google.com/token
authorize_path=https://accounts.google.com/o/oauth2/v2/auth
set_access_durations_action=
protected_resource_url=https://accounts.google.com
scope=openid
local_account_logins=0
client_id=packetfence
description=google openid
domains=https://accounts.google.com
hash_passwords=bcrypt
site=https://accounts.google.com
redirect_url=https://pfcen7dev.lan/oauth2/callback
type=OpenID
```
2. Assign OpenID source to default connection profile
3. Preview

After you accept AUP, portal displays: 
```
Not Implemented

GET to /o/oauth2/v2/auth not supported.
```

**Expected behavior**
You should be redirected to https://accounts.google.com/o/oauth2/v2/auth, not to `/o/oauth2/v2/auth`

**Additional context**
Issue is not present if tests are done directly from captive portal.

**Comment by fdurand** [comment]
The preview is a reverse proxy to the portal, so it rewrite all the links to force to stay on the portal.

It should be possible to allow the redirection but you will need to do something with the redirect_url=https://pfcen7dev.lan/oauth2/callback . This won't work as is since the redirect url will need to take care of the portal_preview url.

Btw if you can provide me a trace of the http request (Live HTTP Headers extention per example).

**Comment by nqb** [comment]
> The preview is a reverse proxy to the portal, so it rewrite all the links to force to stay on the portal.

When we use OAuth or OpenID sources, we need to leave portal to reach identity providers then go back on captive portal.

**Comment by julsemaan** [comment]
That has always been a limitation of the portal preview as @fdurand said because the redirect URL will never work as it runs on port :1443 behind the path /portal_preview/

If you want this to work in the preview mode, you need to set your redirect URL for the OAuth provider for the preview mode specifically.

This means using `https://pfcen7dev.lan:1443/portal_preview/oauth2/callback` as your redirect URL both in the config of PF and in the OpenID configuration

**Comment by nqb** [comment]
I got your point. Thanks for clarification. I will provide HTTP trace.
