### ISSUE TITLE
Self service OS list. When OS is unknown, shows empty label

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5513]
**Describe the bug**
If one of the OSes in the list of the self-service OSes is unknown, it shows an empty label. This can happen if the device was deleted on api.fingerbank.org. We should show a label saying 'Unknown device ($DEVICE_ID)' instead

**Screenshots**
![image](https://user-images.githubusercontent.com/3857942/83627303-b29a7100-a564-11ea-9c35-a50a0388bd62.png)

**Additional context**
conf:
```
[default]
device_registration_allowed_devices=6,7175,15664,20282,39938,15668,38563,33640
```

**Comment by satkunas** [comment]
@julsemaan I recently added the fallback display of the value when a label (or an external search) is empty.

This was done in https://github.com/inverse-inc/packetfence/commit/76fc7bed4464c914ce9d65825082f2788b2c3607#diff-11f9afcb73e5afa6fe34567eed9c5094

Which currently displays:
![Screenshot_20200603_134205](https://user-images.githubusercontent.com/3904468/83669920-548b7f00-a5a0-11ea-87eb-c3f043876c36.png)

Since this field uses an external search, which in this case returns empty - the above fix provides a fallback.

Modifying the label to include "Unknown" would create a special case and requires some additional code for a custom workaround. If you think it's still needed let me know, otherwise update your branch to include the commit above.

**Comment by julsemaan** [comment]
Just putting the ID is fine, are you able to backport this to maintenance/10.0?

**Comment by satkunas** [comment]
> Just putting the ID is fine, are you able to backport this to maintenance/10.0?

Done in https://github.com/inverse-inc/packetfence/commit/c865e9788f1e9048946c9c2057f12c449e62e4a5
