### ISSUE TITLE
API - Database Create timeout

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5550]
**Describe the bug**
Create database fails in configurator due to 504 gateway timeout. The database creation succeeds in the background, but the web admin in left in an unsynchronized state that requires a manual drop of the database and a refresh/reset of the configurator GUI

**To Reproduce**
Install Packetfence on a potato and try to pass the configurator.

**Expected behavior**
Server timeout should allow slower hardware to pass the database creation.

**Additional context**
Significantly increasing the server timeout (from `timeout server 50000`) resolves the problem. Database creation on a 5400rpm drive took 120s to complete.

https://github.com/inverse-inc/packetfence/blob/devel/conf/haproxy-admin.conf.example#L42

**Comment by nqb** [comment]
I've seen same behavior when trying to display ~250 switches in a cluster environment that match [our minimum hardware requirements](https://github.com/inverse-inc/packetfence/blob/13d330e1496ede8f0eb968500fec7426b737e489/docs/PacketFence_Installation_Guide.asciidoc#minimum-hardware-requirements).

During [integration tests](https://github.com/inverse-inc/packetfence/blob/13d330e1496ede8f0eb968500fec7426b737e489/t/venom/pfservers/configurator/40_run_custom_step.yml#L34-L37), I've to increase this timeout too to let PacketFence services start (due to ressources).

I suggest to increase this timeout to 120s like @satkunas proposed.

**Comment by julsemaan** [comment]
I think haproxy-admin should match the values from https://github.com/inverse-inc/packetfence/blob/devel/conf/caddy-services/api.conf.example#L61-L64

And let the api-frontend handle timeouts that are shorter than that if applicable

**Comment by nqb** [comment]
It make sense to me.

Should we do a manual sync ?

**Comment by julsemaan** [comment]
> It make sense to me.
> 
> Should we do a manual sync ?

I think we should for now to get this fixed, then potentially move to a value in pf.conf for the admin panel related timeouts (which we can track in another issue)

That will allow for a faster delivery of the fix

**Comment by satkunas** [comment]
Fixed in https://github.com/inverse-inc/packetfence/pull/6167 by adding pfqueue async call

Closing.
