### ISSUE TITLE
Viewing a local user with a valid_from set to a zero date breaks the form

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5592]
**Describe the bug**
If you view a user with a zero date in the valid_from field like the one below:
```
+-----------+------------------------------+----------------------------------------------------------------------+---------------------+---------------------+-----------------+-------------------------------------+----------+---------+---------------------+-----------------+
| tenant_id | pid                          | password                                                             | valid_from          | expiration          | access_duration | access_level                        | category | sponsor | unregdate           | login_remaining |
+-----------+------------------------------+----------------------------------------------------------------------+---------------------+---------------------+-----------------+-------------------------------------+----------+---------+---------------------+-----------------+
|         0 | inverse                      | {bcrypt}$2a$08$mA0GU1IFeLHhiAbQ/FbFk.8n8H9JUsEkkrQjml1XYziNyFTR5o2Vi | 2020-06-04 00:00:00 | 2021-06-02 12:00:00 | NULL            | ALL                                 |     NULL |       0 | 0000-00-00 00:00:00 |            NULL |
|         2 | bob@example.com              | {bcrypt}$2a$08$asDtzTgROeUf02Mo4LEbbujDTZe9yH08m6t0TagJuOpCMDL65W/fu | 0001-11-28 22:16:14 | 2020-07-13 10:55:34 | 1D              | Node Manager,Security Event Manager |        2 |       0 | 0000-00-00 00:00:00 |            NULL |

```

Then it makes the form break (check the valid_from date field):
![image](https://user-images.githubusercontent.com/3857942/84684995-79b8af80-af07-11ea-8d19-7c57b6b2ab97.png)

**Comment by satkunas** [comment]
@julsemaan this is because we're utilizing Javascript Date on these fields to provide a date-picker. The exact reason this occurs is because of the following, you can verify on any webkit console:

```
// good
(new Date(1900,0,0))
Sun Dec 31 1899 00:00:00 GMT-0500 (Eastern Standard Time)

// same as before
(new Date(0,0,0))
Sun Dec 31 1899 00:00:00 GMT-0500 (Eastern Standard Time)

// bigger fail
(new Date(-1,0,0))
Thu Dec 31 -002 00:00:00 GMT-0456 (Eastern Standard Time)
```
There's no consistency w/ Javascript on dates anytime before `Jan 1 1900`. This includes both the date-picker and any date format validations (except pure regex).

We'll either need to:

* [ ] - Drop the date picker and change these form elements to allow free text.
* [ ] - Deprecate using zero dates altogether.

**Comment by satkunas** [comment]
Temporary workaround pushed in https://github.com/inverse-inc/packetfence/commit/6a28e41da1b0fc4a124be16760de191fa280dcb8, cleanup in https://github.com/inverse-inc/packetfence/commit/2e9bc04051678fafec6a38fd796993477745a160, https://github.com/inverse-inc/packetfence/commit/c73fd5fb31558dcedecb6fbbb02de7c4f0437d93

I changed the `valid_from` and `expiration` input elements from date-pickers to text, in order to minimize changes for the release, we will revisit this again afterwards.

**Comment by satkunas** [comment]
Updating milestone to revisit again later.

**Comment by satkunas** [comment]
More temp workarounds added in https://github.com/inverse-inc/packetfence/commit/f5b014e1077163748c552510715f6e5c9a0900a8 with https://github.com/inverse-inc/packetfence/issues/5598

https://github.com/inverse-inc/packetfence/commit/5e74de6aeebd28a1370cfe01f44d0c6f2e8a447d with https://github.com/inverse-inc/packetfence/issues/5601

**Comment by extrafu** [comment]
@satkunas and @julsemaan are we ok now for the temp fix? if so, let's move it to v11 since we'll have more time to revisit this.

**Comment by satkunas** [comment]
Unable to reproduce with latest devel. Moving milestone for retesting post-gui-perf.

**Comment by satkunas** [comment]
Please retest with new admin ui.

**Comment by julsemaan** [comment]
Still problematic
![image](https://user-images.githubusercontent.com/3857942/114724458-90878880-9d09-11eb-9095-d49754de26b9.png)
