### ISSUE TITLE
Packetfence PKI: update doc

### ISSUE THREAD

**Issue by thijsvdc** [inverse-inc/packetfence#5609]
I'm very happy to see that Packetfence PKI is now integrated. However, the doc (https://packetfence.org/doc/PacketFence_Installation_Guide.html#pf-pki) is not very clear about how to use the CA file for using it with EAP-TLS:

> QDon’t forget to add that Root CA certifiate to the radius configuration to authorize the EAP TLS authentications using the PKI issued certificates.

Can the doc be updated with exact steps on how to do this?
Do we just need to c/p the contents of the CA file on the GUI, put it somewhere in /usr/local/pf/raddb/certs as Custom_CA.pem for example, and reference to it in /usr/local/pf/conf/radiusd/eap.conf as "ca_file = ..."?

This would be a great help.

**Comment by thijsvdc** [comment]
Hi @fdurand, the updated doc is much better, however I'm still doing something wrong I guess:

I created the CA under Configuration > Integration > PKI > Certificate Authorities as explained in the doc. When done, I copied it and went to Configuration > System Configuration > SSL Certificates > Radius, clicked "Edit" and replaced the existing Certification Authority certificate(s) with my new CA cert.

This throws an error: " Failed verifying chain: error stdin: verification failed . Ensure the intermediates certificate file you provided contains all the intermediate certificate authorities in x509 (Apache) format.", unless I uncheck "validate certificate chain".

And indeed: I can only connect using PKI-generated user certificates when selecting "don't validate ca".

Is there still a missing step?

I've tried both on PF 10.0.1 and 10.2.0.

**Comment by myleskeeffe** [comment]
I figured this out earlier today (I think - only got past this step - still got to do the rest aha) - but these are the steps that got me past this:
1. Under Settings > Integration > PKI > Templates, create a new template. I originally tried this with an ECDSA cert/CA - it did not work, but using KEY_RSA with SHA512WithRSA digest appears to work. Set name, email, key size & validity to preference. Under "extended key usage", I added "ServerAuth". I'm assuming this is required - but could also be completely wrong.
2. Upon downloading the cert, use openssl to decrypt and extract the CA cert (which we already have), the Server Cert & Server Private key. [More Info](https://www.ssl.com/how-to/export-certificates-private-key-from-pkcs12-file-with-openssl/)
```openssl pkcs12 -info -in <cert.p12> -nodes``` 
3. In Settings > System Configuration > SSL Certificates > Radius > Edit Radius Certificates, paste in the values from above step. Ensure no extra whitespace/newlines underneath the certificate/key when pasting.
4. Click "Save". I've still got to go through with the rest of the PKI setup to see if this works - but it atleast saved properly - which is giving me hope :stuck_out_tongue: 

Edit: I'm going to say I'm wrong on the requiring ServerAuth bit - just because the documentation uses that cert in the AAC > PKI Providers section.

**Comment by Tan-cerp** [comment]
I stumbled upon this error and actually I solved this by ADDING the generated certificate after the existing CA Cert. I looked for a solution for hours and then noticed that the field for adding the certs is named "Certification Authority certificate(**s**)"... plural. Thus just add it after the ----END CERTIFICATE---- mark and you should be fine.
I realise I'm late to the party but I'm just contributing in case someone else has the same problem. Almost lost my mind on that one.
