### ISSUE TITLE
Maintenance task - Descriptions is not localized

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5836]
**Describe the bug**
When you go in System configuration -> Maintenance, the column Description is not localized. (in the task itself too)

![image](https://user-images.githubusercontent.com/1553962/94184374-ccdcbf80-fe71-11ea-8cd6-bc75e14a73df.png)

**Comment by satkunas** [comment]
We don't normally offer localization on user defined strings, only the column headers:

![Screenshot_20200925_094917](https://user-images.githubusercontent.com/3904468/94274999-6d83bb80-ff14-11ea-9929-c02d5f0ee3bf.png)

However, since these strings are relatively static, should we include them in our translations? @cgx?

**Comment by fdurand** [comment]
it's from *.conf.default so we should translate them.
If the administrator add new configuration with description it will be probably in his native language.

**Comment by satkunas** [comment]
@cgx front-end adjusted with 7c6351a6ab94a3822ec3f8f9626ca90a953dad81
