### ISSUE TITLE
Search within Nodes using the Role Field, and functions of "Starts with" "Contains" "Ends with" is not working

### ISSUE THREAD

**Issue by cdcrawford** [inverse-inc/packetfence#5879]
**Describe the bug**
When searching for a Role (thus far I've only seen it when searching for the role) using Starts with, Contains, or Ends with, yields no results.

**To Reproduce**
1. Go to Notes
2. Hit Advanced Search
3. Change Field to Role
4. Search Function to any of Contains, Starts with, Ends with.
5. Throw a search in there
6. No results.

**Screenshots**
See attached. Error.
![image](https://user-images.githubusercontent.com/3090648/94825011-05354e00-03dc-11eb-94fd-bf0411af9f2d.png)

See attached. Devices who's role starts with "Labs"
![image](https://user-images.githubusercontent.com/3090648/94825164-37df4680-03dc-11eb-8766-1008c73c2801.png)

**Expected behavior**
To display devices that have a role that starts with, contains, or ends with the search string. It does not currently.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 81.0

**Comment by jrouzierinverse** [comment]
We would need to change the frontend to search using 'node_category.name' instead of 'category_id'.

**Comment by julsemaan** [comment]
We should be careful with this change since category_id is indexed in the node table.

If we decide to move forward with making contains work, it should use node_category.name when its contains and category_id when its equals

I believe the behavior of the old admin was to allow only exact matching on that field which we could use as a fix if using a different field based on the operator is too complex in the frontend

**Comment by jrouzierinverse** [comment]
I was considering handling this on the backend.
But going through all the different scenarios I believe it would be better to push that complexity to the frontend.
