### ISSUE TITLE
RADIUS filter attribute search glitch on maintenance/10.0 (most likely applies to devel too)

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5934]
**Describe the bug**
When configuring a RADIUS filter, if you search for an attribute it will work but if you focus out then into the field then you lose the content of the search and are back with the full unfiltered list

**To Reproduce**
1. Create a new RADIUS filter
![image](https://user-images.githubusercontent.com/3857942/96897897-16aeca80-145d-11eb-8619-8ca87ab5ab7f.png)
2. Focus on the field containing Idle-Timeout
3. Search for Timeout
4. Focus out and then back into the field
5. Abracadabra your search has just disappeared :mage_man: 

**Expected behavior**
Search should stay there as long as the field contains my search

**Comment by satkunas** [comment]
@julsemaan try the fix I just pushed. This should retain the search query in the chosen element when focus is lost. There may be other un-intended side-effects with the search in a chosen component that is taggable. If this works I'll back port it to 10.x.

**Comment by satkunas** [comment]
@julsemaan back ported to 10.1 and 10.2.

**Comment by satkunas** [comment]
Will not fix.

This is due to a workaround for an issue with the vue-multiselect component. Retaining the search criteria tricks the user into thinking that the search term is the current value within 'taggable' (user-defined) options. In order to alleviate this confusion the search term is automatically cleared onBlur.
