### ISSUE TITLE
Re-scan on request = client start the scan after fixing the issue = self-remediation

### ISSUE THREAD

**Issue by ZdenekPala** [inverse-inc/packetfence#5983]
**Is your feature request related to a problem? Please describe.**
I created the Scan engine using a WMI Rule. The Scan triggers the Security event. The security event applies the Isolation role with HTML Template.

My observation:
-	When the scan is performed there is 3600 seconds grace period = new scan is not performed again in that period
-	When the Isolation role is applied to the node, the captive portal is presented and the user can “Self-remediate” on the captive portal.
-	If the user clicks the button on the captive portal then the new scan is not performed.
-	I can disable the Auto-Enable button but then the user does not have the option to self-remediate

**Describe the solution you'd like**
The customer wants the following scenario:
-	The WMI test is performed
-	If the node is not compliant then the captive portal is presented with proper information. 
-	Once the user fixes the compliance issue the user should be able to trigger the scan and get to the network if all issues were fixed.

**Comment by nqb** [comment]
When user try to self-remediate, it just reevaluate its access on the network. 

If he matches again same connection profile and your node has a security event opened (by your previous WMI rule using reevaluate_access action), a new WMI scan will be triggered.

But if your node doesn't match anymore WMI rule which triggered previous security_event because it performs actions to remediate, PacketFence will not close automatically current security_event. This means that your node is still isolated.

What you can do on your WMI scan is to create two opposite rules, for instance:
- Antivirus not installed = this rule will trigger a security_event to isolate (for example 300008)
- Antivirus installed = this rule will trigger a security_event to close 300008 security event (for example 300009)

In this situation, when you user clicks on Enable Network after a self-remediation, you should have following behavior:
1. New RADIUS request
1. Post-reg-system scan is not triggered because 300008 is opened
1. 300008 security event should be closed by 300009
1. 300009 security event should be closed
1. Node access is reevaluate again (behavior when you close a security event from another one)
1. New RADIUS request
1. Node connected to the network without any security events opened, a new scan will occur when end of grace time for Post-Reg-System-Scan is reached.

Important notes:
- #6048 prevents you to correctly close a security event at the moment
- Behavior describe here is only valid when first security event use an isolate action. If you use a security event which is directly closed after you WMI scan, behavior is different because Post-Reg-System-Scan grace time will be take into account before running a new WMI scan.

**Comment by nqb** [comment]
WMI has been deprecated in PacketFence v11.
