### ISSUE TITLE
Try to mimic the behaviour of other webauth url for cisco equipment. 

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6063]
In order to standardize the webauth technique in all switch modules we should try to return a redirect url like http://ip_portal/Cisco::WLC?mac=00:11:22:33:44:55&ssid=packetfence&switch_ip=1.2.3.4&bssid=11:22:33:44:55:66

Then we will get rid of the session_id and have the same logic for all webauth and simplify https://github.com/inverse-inc/packetfence/tree/feature/switch-template-accept-url

**Comment by fdurand** [comment]
Tried this and it works perfectly.
So instead of using the session_id we can use the same behaviour as the other vendor.
It will probably simplify the webauth support in the switch templates. @jrouzierinverse @julsemaan what do you think ?

**Comment by julsemaan** [comment]
Agreed that this is a good idea and since the session ID is added dynamically, I think there won't be any changes necessary during the upgrade.

If we deprecate the session ID, lets just make sure we clean it everywhere (locationlog, externalportal.pm, etc)

**Comment by jrouzierinverse** [comment]
Can this be done securely?
Can a random person just type in that URL and bypass everything?

**Comment by julsemaan** [comment]
The controller should be intercepting that (the other vendors do) but we defninitely need to confirm this.

@fdurand, could you check if spoofing is possible ?

**Comment by fdurand** [comment]
it's mac auth, so you can spoof the mac address.
If you change the mac address in the url then you will hit the portal with this mac, you will register then packetfence will try to deauth the "spoofed mac" , so worst case scenario you register another device.
Btw It's the case with the other vendor too.

**Comment by fdurand** [comment]
We can maybe try do create a kind of hash that will be calculated based on the redirect url and then add it at the end.
Then when the device will hit the portal we will be able to validate that the hash prived in the url match the calculated hash..

**Comment by julsemaan** [comment]
The hash idea is good, we could sign the URL with the RADIUS secret.

Not sure it will work with recent versions of the WLC though since they add `&redirect_url=https://zammitcorp.com` at the end which will alter the hash

We could always just hash the MAC address though but as you said spoofing the MAC in the URL is the same as spoofing it on the OS level which is already possible in an open SSID so I'm getting less and less sure this is really necessary

**Comment by jrouzierinverse** [comment]
Why not just using the session_id we have in the locationlog?

**Comment by julsemaan** [comment]
This discussion is specifically around moving away from that session_id to standardize the Cisco integration with the integration with other vendors

**Comment by jrouzierinverse** [comment]
I understand that the discussion is to moving away from the session_id.
However using just the url seems to be insecure.

Hashing does not 100% protect from some form of injection attack.
If I know which hashing algorithm is used and how it is constructed someone can still inject their own values granted it take more effort but not impossible.

Standardizing to use the session_id avoids all of the problems of stuffing all the info in the url.

Here are my questions.
* What are we gaining by going to the url method?
* What are we losing by going to the url method?
* What are we gaining by going to the session_id method?
* What are we losing by going to the session_id method?
* Which one is better in the long run?

I see more downside in the url method since it opens us up to security issues.
To keep the url method secure would require more resources than just using the session_id which we already have.
