### ISSUE TITLE
web admin: RADIUS audit log search is lost when browsing an entry

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6089]
**Describe the bug**
When you do an advanced search in RADIUS Audit log and click on an entry, you're able to see details of entry in same windows. If you close this windows, you get back to RADIUS Audit log but you lost your previous search.

This is really uncomfortable.

**To Reproduce**
1. Go to RADIUS Audit log
2. Search on NAS IP address
3. Click on an entry
4. Close entry

=> You are back on RADIUS audit log without your previous search and you previous search is not active anymore.

**Expected behavior**
Previous search is still here.

**Comment by julsemaan** [comment]
From what I recall before it would leave the previous search but the results weren't representative of the search that was in the field (it was just the listing as if the search wasn't there). The fix @satkunas did to make the field consistent with the results was to strip the search field but it would have been nicer to leave the search in place and get the results consistent with the search

The issue was #5863

**Comment by nqb** [comment]
@satkunas, could you take a look at this one ?

**Comment by satkunas** [comment]
I'll have a look at this one post-10.3. It's a known limitation and more work is scheduled on our roadmap to port the Searches from Vue2 to Vue3. Bumping milestone.

**Comment by extrafu** [comment]
@satkunas Still relevant? If so, can we fix it for v11

**Comment by satkunas** [comment]
This is no longer relevant. The auditing section has been upgraded to the new advanced search which retains all the search criteria across page (re)loads.

**Comment by nqb** [comment]
@satkunas,

I'm able to replicate issue using instructions in "To reproduce" section.

**Comment by extrafu** [comment]
@nqb Please provide RADIUS audit log entires for @satkunas to test.

**Comment by nqb** [comment]
Not able to replicate again with @satkunas. I will close for now and re-open if I notice this behavior again.
