### ISSUE TITLE
Editing Dot1x User requires Registration Window

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#6300]
**Describe the bug**
Editing User crated by Dot1x authentication, requires Registration Window

**To Reproduce**
1. Go to Users
2. Click on User
3. Edit something 
4. Try to Save

**Screenshots**
<img width="1163" alt="Screenshot 2021-04-17 at 11 46 36" src="https://user-images.githubusercontent.com/17347347/115107454-9680a200-9f73-11eb-994e-7ffb5684725c.png">

**Expected behavior**
Should be able to edit and save the user without setting registration window

**Comment by julsemaan** [comment]
Is it when creating a new user or editing a user because the title says creating but the reproducing steps are for editing

**Comment by lyubomirtraykov** [comment]
This is when the user is created by authentication from AD via EAP. When I try to edit and add notes to the user, it cant be saved because, Registration Window is required.

**Comment by julsemaan** [comment]
This is because the admin interface forces you to set a registration window for users that aren't local users (no entry in the password table)

Easy way to replicate:
```
mysql>insert into person(pid,email) VALUES("bobby", "bobby@example.com");
```

And then view the user `bobby` and you'll be forced to set stuff in the Actions tab although the user doesn't have a password entry

@satkunas, can you take a look into this

**Comment by satkunas** [comment]
I've re-implemented the validation exception when a password entry exists. The expiration is only required when a local user exists and is no longer required otherwise.
