### ISSUE TITLE
ZEN hangs on shutdown because systemd-logind is masked

### ISSUE THREAD

**Issue by luizluca** [inverse-inc/packetfence#6418]
**Describe the bug**
If you call poweoff/reboot from a SSH session to a ZEN, SSH session will hang. This breaks batch shutdowns.

This happens because systemd closes network access as soon as it start the reboot/shutdown process. logind is the one responsible to close existing user sessions before network is down, correctly closing the SSH session. However, ZEN has systemd-logind masked.

I can "fix" the issue unmasking systemd-logind. However, it was masked by ZEN for a reason and something might break.

**To Reproduce**
1. ssh to zen
2. poweroff

**Expected behavior**
It should close the SSH session and reboot/poweroff instead of hanging the session.

**Comment by nqb** [comment]
Hello @luizluca,

Thanks for your report.
We masked `systemd-logind` to prevent #4822 issue. Root cause is described [here](https://github.com/inverse-inc/packetfence/issues/4822#issuecomment-533352235).

We are working on EL8 support so we can certainly check if this workaround is still necessary for next release.

**Comment by nqb** [comment]
`systemd-logind` would not be masked anymore on EL starting from PacketFence v11 (see https://github.com/inverse-inc/packetfence/commit/987970d7c33507e7f91c645a6d5036f9f97e925e)
