### ISSUE TITLE
Members of a switch group are not always visible

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#6454]
**Describe the bug**
Members of a switch group can be empty sometime without reason.
If the group has more than few members (like 25), it will be empty all the time.

**To Reproduce**
1. Go to 'Configuration -> Policies and access control -> Switch groups'
2. Click on a group with switches
3. Go to 'Members' tab
4. There are no members even after the page is entirely loaded (no more blue on the top, and even after reload that page)

**Expected behavior**
Show the list of the members

**A solution**
Steps to have the behavior:
1. Go to 'Configuration -> Policies and access control -> Switches'
2. Order Switches by 'Group'
3. Go to Switch groups
4. Click on a group with switches
5. Go to members
6. Members are listed

**Desktop (please complete the following information):**
 - Browser Firefox

**Additional context**
I had few times a 504 API Time Out. But not all the time. So not sure it is related.
But it is not consistant and I don't know why ordering the switches list could help to show the members after that.

**Comment by jrouzierinverse** [comment]
Can you provide your switches.conf

**Comment by jrouzierinverse** [comment]
I found the issue. The problem seems to be the perl modules are loaded lazily to allow a fast startup time.
However this will cause a slow time for the initial API calls to load in the perl module.
This speed hit will happen for each worker and every time a worker dies and is respawned.
We could preload the Controller namespace which will cause all the API calls to become faster but the start and restart service time become slow.
For my basic tests it seems to add ~5 seconds to the start restart time.
So from 2.5 seconds to about 7.12 seconds.
Will reducing the API call from 0.82 seconds to 0.084 seconds.
In my opinion it would be worth it to preload the perl modules to increase the API speed.
What are your thoughts?

**Comment by JeGoi** [comment]
Instead of all API preloaded, could we preload only some selected API requests based on PF conf?
Or the API we know that can failed due the high number of items in a particular section?
For exemple: If (number of switches > 150) then preload switches

**Comment by jrouzierinverse** [comment]
This preloading help for all the APIs not just switches.

**Comment by satkunas** [comment]
@JeGoi please retest and re-assign me if the issue persists.

**Comment by julsemaan** [comment]
@jegoi, please test and confirm if the issue persists

**Comment by JeGoi** [comment]
Tested with 230 switches on PF11 and looks perfect!
I am closing it. Thanks

**Comment by JeGoi** [comment]
I reopen it.
When you change the switch from one group to another group on the switch configuration UI, it is not reflected in the switch group where it has been moved.
In the config file, the new group is well set.
Cache Issue?

**Comment by JeGoi** [comment]
Looks like a cache Issue
