### ISSUE TITLE
v11: roles inherited from switch groups are not visible on switches

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6502]
**Describe the bug**
It's not possible to see which ID has been assigned to a role when you browse a switch which inherited values from a switch group.

**To Reproduce**
1. Create a switch group and set `guest=15`
2. Create a switch, member of switch group created at step 1.
3. Browse your switch (Roles tab)

=> You don't see value of `15` for `guest` role

**Expected behavior**
See value of `guest` role inherited from switch group

**Additional context**
When I click on a switch, I didn't see any GET API calls to `/api/v1/config/IP_OF_SWITCH`, only OPTIONS calls.
If I did a manual API call to `/api/v1/config/IP_OF_SWITCH`, information is correctly returned by API.

**Comment by satkunas** [comment]
@nqb I was able to expand the meta placeholders for 3 of the 4 sections.

@jrouzierinverse The resource meta included `AccessListMapping`, `UrlMapping` and `VlanMapping`, But it did **not include `roleMapping`**, so I was not able to expand these placeholders. I don't know if this is intentional, or if it was missed. Please have a look and let me know if/when you add this field to the meta data.

https://github.com/inverse-inc/packetfence/blob/42f148e0b797e2e096a3c8c2eb63ec2ac0ab4d6c/html/pfappserver/root/src/views/Configuration/switches/config.js#L75-L85

**Comment by satkunas** [comment]
@jrouzierinverse is this what the `ControllerRoleMapping` is for?

If so, should we rename the following?

![Screen Shot 2021-08-12 at 12 52 37 PM](https://user-images.githubusercontent.com/3904468/129236865-66b28b09-f312-4ac0-853b-ecdced6d5ec3.jpg)
