### ISSUE TITLE
Unable to delete a user from the mail page PF11.1

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#6779]
**Describe the bug**
Using the delete feature on the main page of PF 11.1 does not return any results.  Pressing deleted activates the slider feature and moving the cursor again to delete shrinks the slider but takes no action.

Clicking into the user information and preforming the delete from the bottom of the page removes the user as expected.

**To Reproduce**
1. Go to 'User' page
2. Click on the "Delete" button for the user you wish to delete. 
3. See error

**Expected behavior**
Using the delete function from the main interface should result in a deleted user.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chromium
 - Version 96.0.1054.57

**Comment by nqb** [comment]
Hello @RHDHV-simon-sutcliffe,

This bug has already been fixed in maintenance by https://github.com/inverse-inc/packetfence/commit/8449c36b0fc071a134c272e94358d02edf9ca853.

If you are running 11.1.0, you can get this fix using following procedure: https://github.com/inverse-inc/packetfence/commit/8449c36b0fc071a134c272e94358d02edf9ca853
