### ISSUE TITLE
Intune Device Status Compliance Check

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#6824]
We would like to have the ability to make choices as to what to do with devices based on the  InTune compliance state (This could be tied to the realm approach).  

This would then allow us to leverage a consistent device compliance approach for both cloud resources (MS Conditional Access).  

We could then have an additional check before access to the corporate LAN \ WiFi only allowing access to devices based on the same ruleset and moving specific statuses to Isolation \ internet only access.

The state of the device is available using the GraphAPI (Intune section)

https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-compliancestate?view=graph-rest-1.0

The check could be part of the compliance area, or a security event within PF?

**Comment by julsemaan** [comment]
We seem to already do support this via our Intune provisioner:
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/provisioner/intune.pm#L281-L311

To get this in place, configure an Intune provisioner that matches the role(s) of your corporate machines and add it to the right connection profile. It will enforce that all devices matching this provisioner have to both have the agent installed and be compliant, otherwise it will put them in the pending state where they will be isolated on the portal and informed of their non-compliance.

I'm closing this for now, feel free to comment if this is not working as expected

**Comment by PureOxygen-Dev** [comment]
@julsemaan We did indeed check this and it appears to function but not as I expected.

If you look at the returned values from the API call you have three interesting return values

Member | Value | Description
compliant | 1 | Compliant.
noncompliant | 2 | Device is non-compliant and is blocked from corporate resources.
inGracePeriod | 254 | Device is non-compliant but still has access to corporate resources

I am not sure if the code implements the 254.  Where the admin has configured a grace period for non-compliance.

I see we can do something similar within PF but to ease the management of this it might be nice if PF has an option to honer the grace period from InTune allow access.  This could be a switch "On-Off" in PF allowing an admin to toggle between the two giving them choice.

**Comment by PureOxygen-Dev** [comment]
@julsemaan  Did you get anytime to look at this extention to cover the ingrace period.  Would you like me to open a new issues or would you pefer to reopen this one and I will modify the description to better reflect the need.

**Comment by julsemaan** [comment]
Didn't have time to look at it yet but it looks like a valid addition to our code.

We don't have an easy environment to test it so that delays things since it will take more time setting up for testing than doing the actual change in our code

**Comment by PureOxygen-Dev** [comment]
@julsemaan when 12.1 is out we would be happy to test this within devtest cluster environment if that would help get it into 12.2.
