### ISSUE TITLE
PF11.2 DPSK Provisioner ignored Auto Register 

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#6918]
**Describe the bug**
When a new client is pushed through a DPSK provisioner via a connection profile the provisioner is triggered and the DPSK is created a presented, but the client is not set to the status registered.  

**To Reproduce**
1. Create a connection profile with a DPSK provisioner 
2. Set the option on the provisioner to Auto register
3. Put a node through the Connection profile and trigger the provisioner
4. Notice in the Nodes that everything is correct, but the node is not set the "registered" as per the config within the DPSK provisioner.

**Expected behavior**
Node is registered after the provisioner is completed.

**Additional context**
Debian Zen 11,1 upgraded to 11.2.  This bug also was in 11.1

**Comment by julsemaan** [comment]
the DPSK provisioner implies you're going on the captive portal so it doesn't make sense to have it combined with auto-register.

You should have one profile for onboarding people with the DPSK provisioner and one profile for when they connect on the SSID with the DPSK which has autoreg

Reach out to the mailing list for help on configuring

**Comment by PureOxygen-Dev** [comment]
@julsemaan That is how we configured it to get around the above issue, but then it seems strange that the option is there to Auto Register is in the DPSK provisioner if it does not handle the request?  How else could this provisioner be used that would trigger the Auto Register?   Hence I called it out as a bug.

**Comment by chri2** [comment]
Packetfence 13.1

I stumbled over this and spent quite some time debugging and testing before I ended up here.

I'd like to emphasize **'it seems strange that the option is there to Auto Register is in the DPSK provisioner if it does not handle the request? How else could this provisioner be used that would trigger the Auto Register?'**.

> the DPSK provisioner implies you're going on the captive portal so it doesn't make sense to have it combined with auto-register.

My understanding of the situation has been _"A sponsor approved the registration request made by a guest so this action should change the nodes status to registered"_.

The help text for "Auto register" in the provisioner reads _Whether or not devices should be automatically registered on the network **if they are authorized in the provisioner.**_

I do not understand why @julsemaan writes that it makes no sense to:
* have the user fill a registration page leading to (in my case) a sponsor email being send
* authorizing the request by the sponsor
* registering the device because the sponsor authorized it

I ended up trying the same @julsemaan  suggested and @RHDHV-simon-sutcliffe did: auto-register on the profile that I use for the encryped ssid.

## The point I got stuck now is the following:

A device tries to join the encrypted SSID using a wrong PSK **before** it went through the registration portal on the unencrypted SSID.

The AP asks via radius for access for user:MAC/pass:MAC. PF anwers radius 'access-accept' but doesn't return any Tunnel-Type nor a PSK to use. The AP denies the connection. (Why the answer 'access-accept' via radius? Is this part of DPSK? I have authentication source 'local' on that profile and would expect that if the MAC cannot be matched to a users PSK that the radius answer would be 'access-reject'.)

After this a node entry for the mac appears as 'registered' with no role.

When the device now connects to the unencrypted SSID and Firefox detects the need to login to the network the portal web page shown gives a message "Your network access is currently being enabled. Once…" and doesn't ask for an email address anymore (i configured sponsor with a pre-defined sponsor email address).

### Problem

If a user tries to connect to the encrypted ssid having auto-registration enabled in its PF profile before registration through the unencrypted ssid and its portal it is not possible anymore to register. This might happen as well if a DPSK used previously is not valid anymore and the device tries to connect, because the encrypted ssid is still saved on the device as a known network.

## Update: Workaround

Configured a vlan filter to unregister the node when it joins the open registration network.
