### ISSUE TITLE
Server path in packetfence-pki

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#692]
@julsemaan Since you modified a lot also here can you confirm that is not used anyhow?

**Comment by julsemaan** [comment]
What do you mean by server path ?

**Comment by fdurand** [comment]
It's in the pki configuration, we have to define the path of the CA public key certificate (it's ok) but we also have to define the path of the public radius (server) certificate (i don't know why, this certificate is never use on the client side).
For me we have to remove that.

**Comment by julsemaan** [comment]
@whitx told me that it's mandatory to send the CN of the server certificate when configuring an Apple device.

I prefer extracting it from the cert than asking the user for it since it lowers the chances of a code 12 and in the event we need to do more stuff using the cert we'll already have it (like auto configuring the FreeRADIUS server)

I almost re-coded the whole flow to make sure we don't keep useless stuff so I'm 99% sure this has a good reason to be there.

**Comment by whitx** [comment]
Yeah, if I remember well only for Apple it was mandatory to also have the RADIUS server cert, I'll confirm that on Monday tho.

**Comment by whitx** [comment]
Double checked this is what we need
