### ISSUE TITLE
http portal cannot connect to the SMTP server

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#7120]
If the STMP server is set to localhost then the httpd.portal service cannot send an email

**Comment by julsemaan** [comment]
There is no "easy" solution for this. If you want to use the local server as the SMTP relay server, then you need to point the SMTP server value to `100.64.0.1` assuming postfix or another mailserver listens on that. Then if it's postfix, you need to make sure the `100.64.0.0` network is in the mynetworks list so that it counts as local traffic and allows relaying.

We see less and less users using the local postfix instance to send their emails but it does exist.

We can choose between the following:
- Change the SMTP default value to `containers-gateway.internal` and provide an upgrade script which will allow to add the `100.64.0.0` network in the postfix mynetworks. This will work for cases where users are using postfix (the only one our team supports AFAIK)
- Officially deprecate using a local postfix instance to send the emails. Both our alerting section and monit configuration support auth+TLS+SSL and are very flexible. This creates a regression and will require customers to adapt, but we can get rid of handling this external component that is postfix and make everything "PF native"

**Comment by julsemaan** [comment]
As discussed internally:

It's smarter to get pfqueue to send all the emails and make httpd.portal (and others) send their emails via pfqueue.
Pfqueue has and will always have access to the host network for various tasks (like deauth)
This will allow to send emails using 127.0.0.1 and provide backward compatibility for 127.0.0.1+postfix setups

@jrouzierinverse is going to take care of this
