### ISSUE TITLE
Captive Portal Network Detection broken in V12

### ISSUE THREAD

**Issue by PureOxygen-Dev** [inverse-inc/packetfence#7230]
**Describe the bug**
The network detection solution of the captive portal that uses the lookup of /common/network-access-detection.gif is not functioning because the webserver of V12 on no interface is serving that file but causes a redirection.  We have the same set up with 11.2 and the webserver serves the files as expected.  We are running PF 12 in a 3 server cluster.

We are using WebRedirect solution and a Cisco WLC

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure the Captive portal as below leaving the default information in the page but lowering the total timer value.

![image](https://user-images.githubusercontent.com/95610834/192959752-ddca3660-e000-4afb-8b90-edb7d1316793.png)

2. Logon as a guest for example and see the redirect detection page.
3. Watch as the timer progress bar expands for 15 seconds and then you receive an error in red
4. Page then redirects

**Screenshots**
V12 request for /common/network-access-detection.gif
![image](https://user-images.githubusercontent.com/95610834/192960774-4354cf99-4228-462b-9355-309a7c683a72.png)

V11.2 request for /common/network-access-detection.gif
![image](https://user-images.githubusercontent.com/95610834/192960431-3a7f3224-e883-49ca-9b80-a2311da1600e.png)

**Expected behaviour**
We would expect that the V12 webserver would serve the needed file not cause the redirection allowing the network detection code to function correctly. 

** Potentially related Issue **
#7226

**Comment by julsemaan** [comment]
The network detection gif is not hosted on the PacketFence machine. It's hosted on a public machine (owned by us) so that the client tries to fetch that gif and when he gets internet access, he'll be able to grab it from our public server

Technically, the file shouldn't need to be served from the captive portal (others can correct me if I'm wrong)

FYI, the GIF is here: http://192.95.20.194/common/network-access-detection.gif

The network detection works correctly AFAIK in 12.0 based on our tests in our lab (was tested in web-auth and with a reg vlan) so this may be specific to your configuration or something you misconfigured.

Please provide details and screenshots of what is happening when the user is attempting to be granted access to the network versus when you try to fetch the gif manually

**Comment by PureOxygen-Dev** [comment]
Hi julsemaan,

OK clear, what I have found now that the ACL is almost instant (Based on a running ping that starts to respond the moment the user hits the "your granted....") but if you lower the values in the captive portal config too low say 1 second 1 second and 10 seconds it causes a longer delay (about 15 seconds) before it detects the site available.

If the redirection delay is then set to below the time it will take to detect the users gets a red error message for a second or two and then redirection happens.

So for now I think your statement is correct the network detection is working but the GUI allows you to place in figures that should be sanitised.
