### ISSUE TITLE
pf12 - issue with the logo

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7238]
**Describe the bug**
it's not easy to change the logo on the captive portal.

**To Reproduce**
1. Go to connection profile configuration
2. Change the logo
3. Upload the logo on the server
4. The logo doesn't appear since it needs to be uploaded inside the httpd.portal docker image.

**Expected behavior**
We should be able to see the logo
We can maybe create another path on the server for the logo and mount it on httpd.portal docker image.

**Comment by julsemaan** [comment]
100% agreed

For 12.1, it will be addressed by this item in our roadmap: "Rework all the fields that point to a path so that they allow an admin to upload a file via the admin GUI and use that"

I'm not sure it should be a +1 though because it will be very hard to provide a backward compatible way in the maintenance

**Comment by nqb** [comment]
Issue will be automatically fixed on 12.1 thanks to:
- #7261 
- #7288 
- d381fa7b08e046b04ea9c573b1a679e8c32416f4

Closing.
