### ISSUE TITLE
Cluster upgrade to v12: need to expire manually pfconfig namespace to start radiusd

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7244]
**Describe the bug**
During a cluster upgrade from v11 to v12, it was necessary to expire manually `config::Realm` namescape at [following step](https://www.packetfence.org/doc/12.0.0/PacketFence_Clustering_Guide.html#_start_service_on_node_c) because `radiusd-auth` was not able to start. 

`radiusd-auth` was not able to start because `proxy.conf.inc` contains tenant number and we removed all tenant code in v12.0.0.

I dumped `config::Realm` namespace: it doesn't reflect what I had in `realm.conf`. It contained old configuration with tenant numbers.

Before starting services, I ran following commands:
```
/usr/local/pf/bin/pfcmd pfconfig clear_backend
/usr/local/pf/bin/pfcmd configreload hard
```
which should have expire all namespaces.

**To Reproduce**
1. Set up a 11.2 cluster with realms configured
2. Follow upgrade process
3. Try to restart services once node C has been upgraded

=> `radiusd-auth` should fail to start.

**Expected behavior**
 `radiusd-auth` starts correctly.

**Comment by julsemaan** [comment]
I have put some thoughts into this and I attempted a fix that is different from what we discussed (i.e. ensuring a clear_backend works during the upgrade with a valid DB connection)

Prior to 12.0, that didn't happen and that specific problem was handled for when a DB would be in read-only. I wasn't sure why it regressed. Then I remembered this commit 16a376ee6c447daf6ef60ecbefa309d53709eda4 and after reading the code, it seems that when we're fully failing to connect to the DB, we're not recording that we should clear the backend afterwards like with a read-only. Something related to DB connections changed with proxysql and that was the source of that commit and I made it so that when a full DB connection failure happens, then it records that it should clear the backend.

Will it fix it for sure? No, but the chances are good so before I try to workaround it or create complex logic in the upgrade, I wanted to attempt this fix and see if this happens again in our upgrades

**Comment by nqb** [comment]
Thanks @julsemaan.
In case I got same behaviour when upgrading to 12.1, let me know which logs or things I can check to provide feedback.

**Comment by julsemaan** [comment]
> Thanks @julsemaan. In case I got same behaviour when upgrading to 12.1, let me know which logs or things I can check to provide feedback.

Just want to double check, you did have this behavior upgrading to 12.1 which contains the attempted fix? (https://github.com/inverse-inc/packetfence/commit/16a376ee6c447daf6ef60ecbefa309d53709eda4)

**Comment by nqb** [comment]
No. I just want to know if I can provide more debug/log stuff in case I got same behavior once we released 12.1

**Comment by julsemaan** [comment]
So here is what could help:
- pfconfig.log (or journalctl output)
- Before clearing the backend manually, a mysqldump of the keyed table
- The output of the do-upgrade script

**Comment by nqb** [comment]
Did an upgrade yesterday from 11.2 to 12.0 with a configuration in realm.conf and radiusd-auth starts correctly on all nodes.
