### ISSUE TITLE
Portal not accessible when sponsor authentication is enabled

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#728]
That makes activation impossible.

Putting portal on the interface fixes it

**Comment by dwlfrth** [comment]
Still wondering if that shouldn't be considered as a "feature"... no kidding...

With the introduction of the 'portal' interface type, we want to force the admin to specify on which interface the httpd.portal daemon is listening on, both for configurability and for security concerns.

We can continue with the existing approach where we suppose that httpd.portal is also listening on management but that kind of defeats the 'portal' type... But I do agree that a lot of code paths are considering the httpd.portal to be listening de-facto on the management interface.

Solutions:
- Keep it that way and need to manually configure the 'portal' type on the different interfaces that we want httpd.portal to be listening on and document it as it is supposed to be;
- Enforce the 'portal' type on the management interface for the moment;
- Consider (in the code) the management interface as a 'portal' type (in the portal_ints array);

I'm personally in favor of the first option but I agree that I can lead to simple codepaths no longer working due to missing configuration.

Either way, let's talk real quick about this and I'll fix it in a matter of minutes depending on the solution.

**Comment by julsemaan** [comment]
Only thing is that documentation needs to be adapted to the new reality. I have nothing against leaving it closed by the upgrade guide should state all the required changes.

Plus the admin guide should be adapted to include the configuration of the portal interface for the e-mail, sponsor sources config

**Comment by dwlfrth** [comment]
Will not change the actual behavior. Will adjust documentation accordingly.

**Comment by julsemaan** [comment]
@dwlfrth is this in the docs, or not yet ?

**Comment by dwlfrth** [comment]
Should be "fixed" with 5f4fcd90ab3e869f1afdb4bcd5e6be7051764871
Please advise
