### ISSUE TITLE
Self service policy: default configuration

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7346]
**Describe the bug**
On a setup without any configuration, default connection profile doesn't have a self service policy configured.

On 12.1 (currently `devel`), if you try to reach:
  * /status: you have an error message
  * /device-registration: you have a message which tell you that module is not loaded

I expect to see same messages in both cases (module not loaded)

I can be wrong but I'm almost sure, /status was working previously in such configuration.

**Comment by julsemaan** [comment]
`/status` is not supposed to work without a self service policy anymore AFAIK. It did work before but it's been multiple releases that the behavior changed. The error message on /status when the module isn't loaded is not meaningful as you've described and actually throws an exception so we need to handle this cleanly

**Comment by julsemaan** [comment]
I was mistaken, the status page is available without a self service policy and it's a regression in the DPSK detection that is causing this.

I've fixed it but the status page login isn't working (different JS issue), I'll open a separate issue for that

Fixed in ffc9c8106543adc33adcf19479eea5073e98650c

**Comment by nqb** [comment]
Reopening, I would like to document default behavior in documentation.
