### ISSUE TITLE
tests: "Gathering facts" task timed out

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7587]
**Describe the problem**
For some VM (Debian 11 or EL8), Ansible is not able to complete "Gathering Facts" task in "Configure environment variables used for tests" play. The task didn't time out so the job is running for 170 minutes without doing anything.

When GitLab call after_script, we can see that the VM is still reachable because Ansible will gather facts (again).

At this stage, the VM is in pristine state because we only:
- Gather facts (one time)
- Start and enable serial-getty service

Consequently, jobs 

**Mandatory informations**
 * Branch: all maintenance branches
 * Scenario: all scenarios
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/3926221984
   *  https://gitlab.com/inverse-inc/packetfence/-/jobs/3926216596
 
**Symptoms**
How the problem can be identified if it appears again ?

![image](https://user-images.githubusercontent.com/10830260/225239992-fac3fe8d-3f5b-4172-8872-03ceb70c572a.png)

**Comment by nqb** [comment]
@JeGoi, I read it was not really fixed, correct?

**Comment by JeGoi** [comment]
Correct, the previous fix was not enough.
Testing branch based on maintenance 12.0
https://github.com/inverse-inc/packetfence/tree/fix/gathering_facts_test
pipeline: https://gitlab.com/inverse-inc/packetfence/-/pipelines/854065293
Looks like this time, we have the recipe.
Need to move it to devel branch than backport.

**Comment by JeGoi** [comment]
What we have done on all playbooks:
* move the gathering facts as a pre_tasks
* set the default gathering facts as the [min](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/setup.py#L202) with the !all
* add the missing facts, mostly network, that are used by debops collections when needed
* remove the gathering fact for apt update on linux_servers since all linux servers are the same.
