### ISSUE TITLE
i use a packetfence but I am trying to logon with the  down-level user loggin (domain\username) , but it always fails but when logon with userPerncipleName (username@domain.com) it passed, what could I do in the configs to bypass this issue

### ISSUE THREAD

**Issue by karim-kandil** [inverse-inc/packetfence#7720]
i use a packetfence but I am trying to logon with the  down-level user loggin (domain\username) , but it always fails but when logon with userPerncipleName (username@domain.com) it passed, what could I do in the configs to bypass this issue

**Comment by nqb** [comment]
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.

**Comment by AYehia0** [comment]
Hello, @karim-kandil 

Based on the information provided, it seems that you are experiencing authentication issues when using the format "domain\username" to authenticate with your Active Directory. The LDAP filters you have tried so far don't seem to be resolving the issue.

To troubleshoot this problem, I recommend the following steps:

- Verify the correct format: Ensure that you are using the correct format for the "domain\username" syntax. Double-check the domain name and username for any typos or errors.

- Test authentication without LDAP filters: Temporarily remove the LDAP filters from the Active Directory authentication configuration and attempt to authenticate using the "domain\username" format. This will help determine if the filters are causing the issue.

- Check attribute mapping: Confirm that the attribute mapping in your Active Directory authentication source is correctly configured. Ensure that the "UserPrincipalName" attribute is mapped to the "Username Attribute" field, and that the "sAMAccountName" attribute is selected as a search attribute.

- Test with a simple LDAP filter: Instead of using complex regular expressions, try a simple LDAP filter to authenticate using the "sAMAccountName" attribute alone. For example:
(&(objectClass=user)(sAMAccountName=%{Stripped-User-Name}))

- **Enable LDAP debugging: Enable LDAP debugging on your Windows OS to gather more information about the authentication process and any errors that might be occurring. Review the LDAP debug logs to identify any specific error messages or issues.**

- Verify user group membership: Ensure that the users are correctly assigned to the "admins" and "guests" groups in your Active Directory. Check for any discrepancies or issues with the group membership that could affect the authentication rules.

- Review rule configuration: Double-check the configuration of your authentication rules to ensure that they are correctly defined and assigned to the appropriate roles. Verify that the group membership conditions match the actual group names in your Active Directory.

By following these steps, you should be able to identify and resolve the authentication issues you are facing with your Active Directory configuration.
