### ISSUE TITLE
Cannot start ntlm-auth-api on new install

### ISSUE THREAD

**Issue by cahalac** [inverse-inc/packetfence#8169]
Hello, I installed PacketFence 13.2.0 from ISO and when I go to add an Active Directory Domain when I saw the following notification-

![image](https://github.com/inverse-inc/packetfence/assets/159575405/9a9dbfba-b82a-4112-8f8c-9f6cf2484361)

I then clicked on the dropdown for ntlm-auth-api and clicked "Start". When I do this, I get the following error in /usr/local/pf/logs/ntlm-auth-api.log -

`May 31 16:13:43 packetfence ntlm-auth-api-docker-wrapper[15253]: No .env file found in /usr/local/pf/var/conf/ntlm-auth-api.d/. Service unable to start. Do you have a valid domain.conf, or manually edited domain.conf without a pfcmd configreload ?`

Also, the ntlm-auth-api stays off - I am assuming this is needed for connecting to Active Directory? What further steps should I do to resolve this issue?

**Comment by stgmsa** [comment]
Hi @cahalac,

This is an expected behavior since there's nothing in you domain.conf (see the image you posted above, domain configuration is empty).

To integrate PacketFence with Windows Active Directory, you'll need to set up your domain config first, then start `ntlm-auth-api` service from either admin UI or CLI. 

here're some key steps:
1. add your domain settings by clicking the "New Domain" button. Including AD FQDN, IP, DNS, etc... and Save. 
2. start ntlm-auth-api service from admin UI / CLI.
3. check if ntlm-auth-api is running (by refershing the page) or check service status using `pfcmd service pf status`
4. adds corresponding realm config for your domain (if you'll need further authentications based on windows AD) 
5. restart radius-auth services. 

For more detailed information & best practice, please refer to PacketFence's documentation: 
https://www.packetfence.org/support.html#/documentation
Hopefully it works in your case.

**Comment by cahalac** [comment]
Okay, should I make a new issue if I am unable to create a domain? Getting an error code 504 when clicking the blue "Create" button and I figured the issue was with that auth-api not being started but appears to not be the case.

![image](https://github.com/inverse-inc/packetfence/assets/159575405/4985491d-6b8b-4ee0-ace0-9a251fc685f4)

**Comment by cahalac** [comment]
Okay, should I make a new issue if I am unable to create a domain? Getting an error code 504 when clicking the blue "Create" button but I fogured the issue was with that auth-api not being started but appears to not be the case.

![image](https://github.com/inverse-inc/packetfence/assets/159575405/4985491d-6b8b-4ee0-ace0-9a251fc685f4)

**Comment by stgmsa** [comment]
> Okay, should I make a new issue if I am unable to create a domain? Getting an error code 504 when clicking the blue "Create" button and I figured the issue was with that auth-api not being started but appears to not be the case.
> 
> ![image](https://private-user-images.githubusercontent.com/159575405/335667170-4985491d-6b8b-4ee0-ace0-9a251fc685f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODUzNzMsIm5iZiI6MTcxNzE4NTA3MywicGF0aCI6Ii8xNTk1NzU0MDUvMzM1NjY3MTcwLTQ5ODU0OTFkLTZiOGItNGVlMC1hY2UwLTlhMjUxZmM2ODVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxOTUxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDA2YTRiMjRlYjQ0NTc5MTY2OTg5MjdiYzY5NzNkZjA4MGRmMmRmZDkzMDkwODVkOTcxMWZiZWE4NTE5MDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CeyX4WfgFetf2c2-8fO-jqCkaTms6siS34MA5G6whTo)

It might be your PacketFence instance doesn't have access to Windows AD Controller or the DC is not responding within a period of time.
Please check packetfence logs and the connectivity between DC and PacketFence. Raise an issue if there's a bug indeed.
