### ISSUE TITLE
Passthroughs broken in clustered mode depending on the dns used

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence#820]
We return both servers IPs as nameservers in clustered mode.
That does not play well with passthroughs since pfdns may not see the request and add the passthrough if the dns request goes to the other server.

There's a proposed fix in #821

**Comment by julsemaan** [comment]
I've made something similar here 2 weeks ago : 
https://github.com/inverse-inc/packetfence/pull/760

**Comment by julsemaan** [comment]
I don't think we should simply return the cluster IP since it makes it less cool (couldn't come up with a better word...)

I think we should instead rework the way we create passthroughs in ipset and add all the IPs on start based on the list we currently have. Then when config gets changed/reloaded we apply the proper changes.

Other ideas are also welcome, I just don't think we should ditch load balancing because a feature we have doesn't support it well...

**Comment by fdurand** [comment]
Not sure we have to add all IPs on start because dns entries have a TTL and we have to use it to expire the ipset and find a way to sync both servers. Also we can add wildcard in passthroughs so ...

**Comment by julsemaan** [comment]
Very true @fdurand, especially for the wildcards.

Synching ipsets could be interesting. I guess we won't find an easy answer to this then
