### ISSUE TITLE
pfdocs: invalid link in export_import_mechanism.asciidoc pointing to #_restart_all_packetfence_services

### ISSUE THREAD

**Issue by micjurek** [inverse-inc/packetfence#8266]
**Describe the bug**
Import/Export documentation (available at https://github.com/inverse-inc/packetfence/blob/devel/docs/installation/export_import_mechanism.asciidoc) contains invalid link (in the Import on new installation section -> restart services).

It is pointing to: https://github.com/inverse-inc/packetfence/blob/devel/docs/installation/PacketFence_Upgrade_Guide.asciidoc#_restart_all_packetfence_services
Instead of to: https://github.com/inverse-inc/packetfence/blob/devel/docs/common/restart.asciidoc

**Screenshots**
![image](https://github.com/user-attachments/assets/54f4505e-68bb-4262-981c-a3fd821756b3)
VVV
![image](https://github.com/user-attachments/assets/e9e97662-0654-4a70-85b1-22adf8f2c547)

**Comment by JeGoi** [comment]
Hi @micjurek,

Github is not the right place to follow links due to aisciidoc compilation during the released process.
So, you should use the following link https://www.packetfence.org/doc/PacketFence_Installation_Guide.html in order to have the compiled instructions.

That been said, you are right that the link is broken.
It should be something like ./doc/PacketFence_Upgrade_Guide.html#_restart_packetfence_services

I will provide a fix in few minutes.
Thanks

**Comment by JeGoi** [comment]
https://github.com/inverse-inc/packetfence/tree/fix/8266
