### ISSUE TITLE
E-mail guest registration misbehaviour

### ISSUE THREAD

**Issue by istvanbernath** [inverse-inc/packetfence#836]
Hi,

After upgrading to PacketFence 5.3.1 on a Debian Wheezy installation I've just
recognized that guest registration via e-mail is practically out of function.
The same I've experienced on a fresh installation.
When somebody tries to register as a guest via e-mail, the activation mail gets delivered
and the internet connection opens up.
One can read the activation mail and it is possible to tap the "Activate Your Network Access"
field. A browser window pops up, but the browser states that the page can not be accessed
since there is no connection to the server.
After 10 minutes, or after manually unregistering the node, it is possible to reread the page
and one gets the message "Access to the guest network has been granted until ." Notice that
no deadline time provided in the message.
The node becomes registered with "Role" guest, but the "Unregistration" field is empty.

Sponsor registration works even worse, since the activation link results all the time in
"Unable to connect".

The SMS registration woks great.

Is there some new configuration parameter I'm not aware of?

Best Regards
Istvan

**Comment by dwlfrth** [comment]
Hello Istvan,

Please make sure to add the 'portal' type to the existing 'management' interface.
This can be done either by modifying the file manually (type=management becomes type=management,portal) or by going through the admin web GUI and on the management interface, add the 'portal' additional listening daemon. If you go with the manual way, don't forget a '/usr/local/pf/bin/pfcmd configreload hard' for the change to take place.

On a side note, such issues should be discussed on the mailing-list and not on Github issue, which is why I'm closing it. If you need any more help, please use the mailing-list (http://www.packetfence.org/support/community.html)

Thanks!
