### ISSUE TITLE
Docs Directory

### ISSUE THREAD

**Issue by jkoch22** [inverse-inc/packetfence#8376]
**Describe the bug**
New installation of PacketFence 14.0 using Debian installer doesn't include /usr/local/pf/docs

**To Reproduce**
1. Install using latest PacketFence ISO
2. cd /usr/local/pf/docs/ - Directory is non-existent

**Expected behavior**
"docs" directory exists with all documentation .html files

**Comment by E-Thang** [comment]
Also, missing the docs folder blocks rebuilding the httpd.admin_dispatcher docker container

**Comment by JeGoi** [comment]
Yes @jkoch22  it make sens. It has been containerized and it is in the container now.
Yes @E-ThanG  if you want to rebuild the container you need that directory.
BUT it is not a issue on the ISO
It is the same with a default installation:
```
root@172-233-238-244:~# ls -la /usr/local/pf/docs
ls: cannot access '/usr/local/pf/docs': No such file or directory
```

**Comment by jkoch22** [comment]
@JeGoi I agree that it's not an issue with the ISO. I've spent a bit of time looking into this issue today and I see that in the Dockerfile for httpd.admin_dispatcher container it is built by copying the"docs" folder. It then takes those .asciidoc files and converts them to html within the docker container. The issue is that these don't exist so they never get copied over. This causes the admin portal to not show the documentation and return a 404 when loaded. I'm not sure if you're referring to another container or perhaps another process that loads these but this is what I could find regarding this issue. Thanks!

https://github.com/inverse-inc/packetfence/blob/a0e51cd82c2b93c367d44403ab68adc0f945103a/containers/httpd.admin_dispatcher/Dockerfile#L20

**Comment by JeGoi** [comment]
@jkoch22 As I already wrote, it is true that you will need them ONLY IF you rebuild some containers. In that case, you are right docs is only used by httpd.admin_dispatcher.
And rebuilding containers is something that we do not recommend because, it will be overwritten at each upgrade/update of PacketFence. So, you will have to rebuild it.

If you need something that is not there by default, please fill free to open a feature request or a PR in order to have it included in the code. We will be pleased to add it if it brings value to PacketFence.

Thanks for using PacketFence.
