### ISSUE TITLE
Impossible to get past network in configurator

### ISSUE THREAD

**Issue by juchiu** [inverse-inc/packetfence#842]
When trying to configure network interfaces, and setting its type, it resets the other interfaces. 

For example, when setting the second interface to isolation, all the rest are also set to isolation. Same thing happens with management and registration. This makes it impossible to finish with installation.

This happens with 5.3.1 on Ubuntu, Centos, and the provided OVF.

**Comment by julsemaan** [comment]
Please post a screenshot of your network configuration in the configurator.

**Comment by juchiu** [comment]
![Screenshot](http://i58.tinypic.com/68bmmd.png)
Ignoring that the 3 NICs are on the same network...

The issue comes up when using 3 NICs, or using 1 NIC with 3 VLANs.

**Comment by julsemaan** [comment]
Isolation and registration need to be different networks than management by design

There is no point into having the registration network be the same as the management network

That's your issue.

Do it on three different networks and it will work.

**Comment by extrafu** [comment]
Shouldn't we add some checks on our end about this and warn the OP about it?

**Comment by julsemaan** [comment]
Thought about it before closing but it seems a bit obvious to me but we do see this issue coming each month.

I don't think we should prevent people from putting more than 1 interface in the same network and we should make them the same type like we do now, otherwise that won't make any sense in the config afterwards.

Best I came up with would be a warning at the top of the page when the editing modal closes

**Comment by extrafu** [comment]
If the issue pops up every month, we need to fix it :)

**Comment by julsemaan** [comment]
Not really a true issue but more a misconfig from the user IMO but yes that could deserve a little warning.

I know I'm the one who misused issue :)

I'll open the issue for the warning
