### ISSUE TITLE
Access filter engine namespace doesn't have a parent config

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#987]
It's impossible to start pfconfig on devel because of that

**Comment by jrouzierinverse** [comment]
I am not having this issue in my devel environment.

pfconfig::namespaces::FilterEngine::AccessScopes is a base class that should implement the parentConfig method.

Also pfconfig::namespaces::FilterEngine::AccessScopes is never loaded by pfconfig::manager.

So can you provide more detail because I am in the dark on why this would happen.
